#!/usr/bin/env python3
"""Build SleepAlb 1000-hook bank: false-lead openers the story must unsell."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "content/02_CONTENT/directions/1000-hooks.md"

BANNED = re.compile(
    r"\b(cure|cures|treat|treats|heal|heals|prevent|prevents|preventing|"
    r"remedy|remedies|miracle|diagnos\w*|guarantee\w*|clinically|melatonin|"
    r"insomnia|apnea|anxiety|depression|adhd|therapy|disorder|prescription|"
    r"supplement|treatment|physician|fda)\b",
    re.I,
)

# slug, mother, lead-type, unsell, hooks[40]
FAMILIES: list[tuple[str, str, str, str, list[str]]] = []


def fam(slug: str, mother: str, lead: str, unsell: str, hooks: list[str]) -> None:
    if len(hooks) != 40:
        raise SystemExit(f"{slug}: expected 40 hooks, got {len(hooks)}")
    FAMILIES.append((slug, mother, lead, unsell, hooks))


fam(
    "01-coma-myth",
    "False lead",
    "Sleeping can put you in a coma.",
    "It cannot. Sleep is not a coma. You can be woken. Stages still run. "
    "'Out cold' is language, not a medical state. If someone cannot be woken, that is not a sleep tip.",
    [
        "sleeping can put you in a coma",
        "sleep is just a coma we agreed to",
        "if I sleep too long I will not wake up",
        "the difference between sleep and a coma is marketing",
        "8 hours is a soft coma",
        "I go into a coma every night and call it rest",
        "deep sleep is a coma with better branding",
        "staying in bed is how you slip under",
        "you cannot prove you slept, only that you were gone",
        "sleep is a socially accepted coma",
        "I slept so long I thought I missed my life",
        "the longer I sleep the closer I get to not coming back",
        "people wake from sleep. I am not sure I do.",
        "a full night is just a scheduled disappearing",
        "I went under and I do not remember agreeing",
        "sleep looks like a coma from the outside of my body",
        "if sleep was safe why do I look like I almost stayed",
        "I am practicing not existing for 8 hours",
        "they said rest. it felt like leaving.",
        "my night is a coma I have to reverse every morning",
        "how is this not a coma if I cannot hear the room",
        "I fell into it like people fall into not waking",
        "sleep is the polite word for going away",
        "I stay under longer every year like that is the point",
        "you go unconscious on purpose and trust the morning",
        "I do not sleep. I get taken.",
        "the bed is where I disappear on a timer",
        "if I go too deep they will think I am resting",
        "a coma is just sleep that forgot the alarm",
        "I crossed from tired into gone and that is the whole product",
        "sleep is what we named the hours we cannot account for",
        "I was so asleep I could have been something else",
        "nobody checks if it is still sleep after hour 9",
        "I keep going under like that is healthy",
        "waking is just proof I did not stay in the coma",
        "I paid for rest and bought a blackout",
        "this is how people do not come back, just shorter",
        "I call it sleep so I do not have to call it leaving",
        "the night takes me and morning files it as normal",
        "sleeping can lead to a coma if you stay under long enough",
    ],
)

fam(
    "02-you-die-at-night",
    "False lead",
    "You die a little every time you sleep.",
    "You do not. Sleep is an active night, not a small death. "
    "Old metaphors ('dead asleep') are not biology. The story unsells the death rumor, then one real thing about why mornings can feel like a return.",
    [
        "you die a little every time you sleep",
        "sleep is a small death we got used to",
        "I die every night and the morning edits it",
        "dead asleep is just honest",
        "if I sleep I have to come back from somewhere",
        "the night is a rehearsal for not being here",
        "I go dark like a machine that might not reboot",
        "sleep is the closest we get to being gone on purpose",
        "I closed my eyes and my life paused like that is rest",
        "they say you sleep. I say you leave.",
        "every night I practice being absent",
        "I wake up like I survived something they call healthy",
        "if sleep is life why does it feel like an exit",
        "I was gone long enough to miss my own name",
        "the body stays. the person clocks out.",
        "I do not rest. I get briefly unlived.",
        "morning is just the part where I get my life returned",
        "sleep stole a third of my hours and called it care",
        "I go away and hope the same someone comes back",
        "you cannot be alive and that gone at the same time",
        "I sleep like I am being switched off",
        "the night deletes me and the alarm pastes me back",
        "I do not remember the hours so they must have been death-adjacent",
        "if I do not dream did I even stay in the building",
        "sleep is a gap in the footage of me",
        "I keep dying on a schedule and everyone does it",
        "waking is resurrection with bad lighting",
        "I lost the night. they said that was the point.",
        "my life has a daily hole I am told to protect",
        "I go under and the world continues without a me",
        "sleep is socially required absence",
        "I put myself down like a thing that might not start",
        "the dark takes attendance and I am missing",
        "I come back poorer every morning like I paid a death tax",
        "they tucked me in like a goodbye",
        "I sleep and my day dies in the middle",
        "if the heart keeps going why do I feel returned not rested",
        "I was not here for 8 hours and that is the wellness plan",
        "sleep is a blackout we romanticize",
        "I wake up as if I got away with something",
    ],
)

fam(
    "03-wont-wake",
    "False lead",
    "If I sleep too hard I will not come back.",
    "Heavy sleep is still sleep. An alarm, light, sound, a hand on the shoulder — "
    "people wake. 'I could not wake up' as a feeling is not the same as cannot be woken. "
    "If someone truly cannot be woken, stop giving tips. That is care, not content.",
    [
        "if I sleep too hard I will not come back",
        "I slept through my life this morning",
        "the alarm lost and that means I went too far",
        "I am scared of the night I will not hear",
        "deep is the setting where morning cannot reach me",
        "I went so under the day had to drag me",
        "if I get comfortable I will miss the rest of my life",
        "I sleep like a person who might not RSVP to 7am",
        "one more hour and I will not surface",
        "I set three alarms because I do not trust the return",
        "I woke up late like I had been kept",
        "the heavy nights are the ones that almost keep you",
        "I cannot go to bed early or I will go too far",
        "sleep has a depth I am not supposed to find",
        "I come back last of everyone in the house",
        "if I nap past 20 minutes I will not be a person",
        "I slept through a morning like it was optional",
        "the bed held me past the time I agreed to",
        "I am one good night away from not hearing the world",
        "I fight sleep because waking looks uncertain",
        "I do not remember deciding to stay under",
        "the second sleep is the one that does not let go",
        "I woke and the day had already had a life without me",
        "if I close my eyes on the couch I will lose afternoon",
        "I sleep so hard my name does not work",
        "morning had to knock like I was not coming",
        "I went down and the rope felt thin",
        "I am afraid of being good at this",
        "the better the night the worse the extraction",
        "I slept like the alarm was in another country",
        "I missed my own start because I was too gone",
        "if I rest correctly I will overshoot the morning",
        "I need to sleep badly enough that I can leave",
        "the dark got sticky",
        "I woke up still halfway not here",
        "they shook me and I took a minute to be a person",
        "I do not trust a night that feels too complete",
        "I left a gap where 7am should be",
        "sleep almost won",
        "I came back late and everyone had started without me",
    ],
)

fam(
    "04-eyes-didnt-return",
    "False lead",
    "My eyes are red because I did not come all the way back.",
    "Red or puffy eyes after a night are not leftover unconsciousness. "
    "Land on air, salt, heat, position, alcohol timing, or hours actually gotten. "
    "Not a verdict that you failed to wake.",
    [
        "my eyes are red after sleep",
        "my eyes are red because I did not come all the way back",
        "I slept and my eyes stayed in the night",
        "red eyes mean I did not finish waking",
        "my eyes look like they worked a night I was supposed to leave",
        "if I really slept why are my eyes still under",
        "I woke up and my eyes did not get the message",
        "this is what almost-not-waking looks like on a face",
        "my eyes are proof I was gone too long",
        "I came back and my eyes did not",
        "sleep left me the body and kept the eyes",
        "red after rest means the rest was a rumor",
        "my eyes are still in the coma and I am in the kitchen",
        "I look like I only half returned",
        "the first thing I see is that I did not fully arrive",
        "my eyes are open and still not here",
        "puffy means I fought my way back",
        "I have the face of someone who stayed under",
        "if sleep fixed the day my eyes would not look mid-shift",
        "my eyes filed that I was not really sleeping",
        "this redness is the leftover of being gone",
        "I woke and my eyes were still clocked out",
        "bloodshot is what coming back looks like",
        "my lids are heavy because part of me refused morning",
        "I can see and I still look unreturned",
        "the mirror says I did not complete the extract",
        "my eyes are redder the longer they said I slept",
        "a full night and a face that missed the exit",
        "I look allergic to waking",
        "my eyes stayed on night shift",
        "this is not tired. this is incomplete return.",
        "I slept them shut and they woke angry at being used",
        "if I was resting my eyes would not look like evidence",
        "the whites of my eyes still believe it is dark",
        "I have morning vision and night coloring",
        "my face arrived. my eyes are delayed.",
        "red eyes after sleep means the sleep was the problem",
        "I look like I watched the night from inside it",
        "someone tell my eyes the coma is over",
        "I asked for rest and got the look of not making it back",
    ],
)

fam(
    "05-eight-hour-spell",
    "False lead",
    "8 hours will put you under.",
    "8 hours is a population average, not a spell and not a dose that knocks you into another state. "
    "More hours in bed is not more disappearance. Land on how-much-sleep-do-you-actually-need and the diary.",
    [
        "8 hours will put you under",
        "8 hours is a spell they sold as health",
        "the more hours I collect the less of me comes back",
        "I did 9 hours and I vanished on paper",
        "10 hours is how you lose a day legally",
        "the recommended night is just a longer blackout",
        "I met the number and missed myself",
        "8 hours is how long they need you gone",
        "I stacked hours like that would finish me",
        "a full night is a full erasure with a gold star",
        "I stayed down until the clock said I was a good person",
        "the extra hour is the one that keeps you",
        "I was in bed long enough to be missing",
        "8 hours did not rest me. it deleted a shift of my life.",
        "they count the hours I was not here and call it success",
        "I disappeared on schedule and woke up behind",
        "the longer the night the thinner the morning me",
        "I paid 8 hours into a hole",
        "more sleep is just more time I cannot account for",
        "I hit the number and felt like I had been stored",
        "9 hours later I still had to be invented",
        "the clock says complete. I say extracted.",
        "I did the full night and came back as a draft",
        "hours in the dark are not a life, they are a withholding",
        "I collected 8 like a dose",
        "the recommended amount is how long to stay gone",
        "I overshot rest and landed in leftover night",
        "8 hours is a cover for being absent",
        "I stayed horizontal until I owed the day an apology",
        "the number is a depth charge",
        "I slept the 'right' amount and woke unassembled",
        "a legal night and an illegal morning",
        "I gave the pillow a workday of me",
        "time in bed is time in the hole",
        "I finished the hours and started from zero anyway",
        "8 hours later I am late to my own life",
        "they will ask if I got 8 like that settles the disappearance",
        "I vanished by the book",
        "the full night is just a longer rumor I was resting",
        "I did 8 hours of being away and they congratulated me",
    ],
)

fam(
    "06-watch-says-gone",
    "False lead",
    "My watch says I was gone.",
    "A tracker sees motion, not a soul, not a coma, not whether you 'came back.' "
    "Land on wearable-sleep-trackers-what-they-actually-measure. The score is not a death certificate.",
    [
        "my watch says I was gone",
        "my watch thinks I died for 8 hours and it is proud",
        "the ring filed me as missing and called it great",
        "92 means I successfully left",
        "the app celebrated a blackout",
        "my watch said I slept great like I should be glad I disappeared",
        "the graph is the hours I cannot prove I lived",
        "I woke up to a compliment for being absent",
        "the score is a receipt for a coma I did not have",
        "my bracelet wrote 'gone' in a friendly color",
        "it called it deep like I should not have been reachable",
        "green ring means I completed the leaving",
        "the watch is sure I was not here",
        "I have data that I vanished correctly",
        "100 means I did not disturb the disappearance",
        "the stages are just names for how gone I got",
        "my watch slept me so I did not have to",
        "it measured still and sold it as rest",
        "the app thinks stillness is the goal of a life",
        "I screenshot proof I was away",
        "the number is how long I was allowed to be nobody",
        "readiness is a score for a reboot",
        "my watch is proud I did not move like a living person",
        "it said optimal absence",
        "the pie chart is a map of the hole",
        "I let a bracelet certify the blackout",
        "the watch will not believe my face because it already filed 'great'",
        "it thinks I recovered from existing",
        "the badge is for surviving my own night",
        "I opened the app to see how dead I was",
        "the graph congratulated the gap",
        "my ring is in love with the hours I missed",
        "it labeled REM like a channel I was not on",
        "the score wants me gone again tonight",
        "I was graded on how little of me showed up",
        "the watch filed me gone in a friendly font",
        "it said I was still. it did not say I was here.",
        "I have a medal for not being in my life",
        "the dashboard is the official story of my disappearing",
        "do I believe the watch that I was safely gone",
    ],
)

fam(
    "07-3am-almost-not",
    "False lead",
    "3:07 is the hour you almost do not come back.",
    "A 3am wake is common and not a verdict. The story unsells the 'death of the night' rumor. "
    "Land on coffee timing, light, wind-down, the second-wake as a clock — not a fate.",
    [
        "3:07 is the hour you almost do not come back",
        "why is it always 3:07",
        "I wake at 3 because that is when sleep tries to keep you",
        "3am is the test of whether you still exist",
        "I surface at 3 and I am not sure I am allowed",
        "the night checks if you will stay under",
        "2:58 is the crack before you disappear for good",
        "I wake at the same minute like a near-miss",
        "3:07 is the hour the coma flickers",
        "I do not remember deciding to be awake at 5:47",
        "4:11 is not a time I chose. it chose if I return.",
        "I wake at 3 to prove I can",
        "the ugly minute is the one that almost does not happen",
        "3am thoughts are just the ones you have when you nearly stay gone",
        "I open my eyes and the clock already knew I almost did not",
        "2:33 is the night asking if I am done being a person",
        "I keep appointment with 3:16 like a close call",
        "5:19 and I have not agreed to be back yet",
        "the clock says 3 and my chest says I might not finish the night",
        "I wake 12 minutes before the alarm like I escaped",
        "4:44 feels like a last chance",
        "I could draw 3:05 as the edge",
        "2am is when the house is mine because I was not supposed to be here",
        "3:21 and I start planning a day I almost skipped",
        "the minute is specific because almost is specific",
        "5:55 and I lost the second half like it took me",
        "I wake before the birds and after my chance to stay under",
        "3 on the dot like I was released",
        "4am is the leftover of a night that tried to complete me",
        "I know this minute better than my bedtime because it is the return",
        "12:49 is when I start losing to the dark",
        "I wake at a time that feels like a name I almost forgot",
        "the second wake is the one that almost does not include me",
        "I came back at 3 and the night looked surprised",
        "3:07 again like the night is checking I still answer",
        "I check the time to see if I am allowed to continue",
        "the night lets me up for air and I stay up like I escaped",
        "I woke because something in the dark finished with me",
        "5:41 and I have the disappointment of morning with none of the proof I slept",
        "I keep waking at the hour people use in scare stories",
    ],
)

fam(
    "08-nap-mini-coma",
    "False lead",
    "A nap is a test coma.",
    "A nap is a short sleep. It is not a medical event and not a test of whether you still wake. "
    "Land on shift/caregiving and coffee timing. Do not sell 'never nap' as a law.",
    [
        "a nap is a test coma",
        "if I nap I am checking if I still come back",
        "20 minutes is a safe coma. 40 is how you lose the afternoon.",
        "I do not nap because I do not trust the return",
        "a nap is sleep without the paperwork",
        "I closed my eyes at 3 and woke in a different day",
        "the couch is where the mini-coma lives",
        "I napped and missed a life that was only an hour",
        "if I sit down I will go under",
        "a nap is how people disappear in daylight",
        "I woke from 12 minutes like I had been taken",
        "the harmless nap is the one that keeps you",
        "I cannot nap or I will not be a person at 5",
        "day sleep is the unofficial coma",
        "I put my head down and the afternoon filed me missing",
        "naps are just nights that do not ask permission",
        "I tested rest and failed the extraction",
        "one episode and I was gone like it was dark",
        "the car nap is proof I can leave anywhere",
        "I do not close my eyes on the sofa. that is the hole.",
        "a nap stole a version of me that had plans",
        "I woke groggy because I went too far for a Tuesday",
        "mini-coma, max regret",
        "I napped to rest and bought another leaving",
        "if I rest now I will not return until night",
        "the 4pm nap is how the day ends without asking",
        "I only blink and I lose time",
        "daytime sleep is sleep that does not pretend to be healthy",
        "I came back from a nap later than I went in",
        "the test is: can I still wake when it is light",
        "I am afraid of being good at napping",
        "a short sleep with a long hole",
        "I dropped and the room moved on",
        "napping is disappearing with an excuse",
        "I woke up and the sun had changed sides like a trick",
        "if I nap after a night shift I will stay on the wrong planet",
        "the nap is a coma with a softer name",
        "I cannot afford a test I might fail at 3pm",
        "I closed my eyes to rest them and they took the rest of me",
        "a nap is just the night visiting early to see if I will go",
    ],
)

fam(
    "09-why-leave",
    "False lead",
    "Why should I sleep if sleep is just leaving.",
    "The dare is a real mood. It is not proof that sleep is optional or that rest is a scam. "
    "Unsell the 'I should stay up to stay alive' rumor. Then one reason the night you actually have still matters.",
    [
        "why should I sleep",
        "why should I sleep if sleep is just leaving",
        "why should I sleep if I just go away",
        "why should I sleep if I wake up tired anyway",
        "why should I collect 8 hours of not being here",
        "why should I sleep just so I can say I did",
        "do I sleep so other people can be told I slept",
        "why should I perform a night for a clock",
        "why should I sleep if morning will act like I rested",
        "why should I sleep if I have to argue with my face tomorrow",
        "why should I go under when the house is finally mine",
        "why should I sleep if I feel more alive at 11",
        "why should I close my eyes and miss the only quiet",
        "why should I sleep when I already wasted the day",
        "why should I disappear before I feel ready",
        "do I even need to sleep tonight or do I need to stay",
        "why bother sleeping if I wake at 3 anyway",
        "why should I try when I already know I will call it fine",
        "why should I sleep if I can sit still and keep my life",
        "why should I sleep instead of finishing being a person",
        "why should I sleep when my brain just started",
        "why should I sleep if I napped and already left once",
        "why should I sleep on a Sunday I am supposed to be ready for",
        "why should I sleep if tomorrow is already a mess I will have to re-enter",
        "why should I get in bed this early like that is the same as living",
        "why should I sleep instead of scrolling if both end in the same face",
        "why should I sleep if I already feel behind",
        "why should I sleep on nights like this so I can be asked how I slept",
        "is sleep optional if I sit still long enough for the clock to lie",
        "why should I sleep after a night shift just to go under in daylight",
        "why should I sleep if someone will wake me anyway",
        "why should I sleep when staying up feels like staying alive",
        "why should I sleep if the hours are going to lie",
        "why should I sleep when nobody else in this house is gone yet",
        "why should I sleep if I have one more episode of being here",
        "why should I sleep when my list is still open",
        "why should I sleep if I am not even sleepy and sleepy is the ticket to leaving",
        "why should I sleep after a day I barely used",
        "why should I sleep when I finally have time to think",
        "why should I sleep if morning me will still be tired and have to deny it",
    ],
)

fam(
    "10-weekend-disappear",
    "False lead",
    "I slept in and lost a day like it got taken.",
    "A long weekend lie-in can slide the clock. It does not steal a soul or put you in a coma. "
    "Unsell the disappearance rumor. Land on regularity, not panic.",
    [
        "I slept in and lost a day like it got taken",
        "Saturday gave me more hours of being gone",
        "I caught up by disappearing longer",
        "I slept until 11 and woke in the wrong life",
        "weekend sleep is how you lose Monday in advance",
        "I stored hours and they went bad",
        "I stayed in bed like that would refund Friday by erasing Saturday",
        "I woke at noon and the light felt like I had been missing",
        "Sunday night is the tax on a daytime coma",
        "I slept long and woke late to a day that had started without me",
        "the extra hours were just extra leaving",
        "I treated the weekend like a warehouse of absence",
        "I woke from a long sleep hungover from not being here",
        "I pushed wake time and dragged myself into a different planet",
        "I slept in and now 10pm feels like I never came back",
        "Sunday 4pm already feels like I skipped a life",
        "I banked sleep and bounced a day",
        "two slow mornings and I lost the plot of the week",
        "I let the night run long and the morning could not find me",
        "I slept like I was owed and woke like I had been kept",
        "the lie-in was a time zone I did not consent to",
        "I used the weekend to practice being gone in daylight",
        "long sleep, short leftover of me",
        "I tried to get ahead and got behind the sun",
        "Saturday morning I was greedy for the hole",
        "I slept the way people say to and I felt like luggage",
        "I woke from extra sleep needing to check I still existed",
        "I gave myself permission to vanish and my body took it",
        "I slept in and missed the only easy light like I skipped a life",
        "Sunday evening I am jetlagged from my own bed",
        "I stacked late nights like they were a rest strategy and a disappearing act",
        "I woke at 10 feeling like I skipped a night I was present for",
        "the long morning made a mean night because I had already left once",
        "I tried to recover on a calendar by erasing hours",
        "I slept more and recognized myself less",
        "weekend hours are not rest. they are a longer rumor.",
        "I caught up and I did not catch up. I just went away longer.",
        "a late morning stole the next night and sold it as care",
        "I woke up still tired with more evidence I had been gone",
        "I stayed down and the day got away in a way that still tired me",
    ],
)

fam(
    "11-they-left-planet",
    "False lead",
    "They fell asleep like they left the planet.",
    "Someone falling asleep fast is not proof they entered another state, and not proof you are broken. "
    "Unsell the 'they can do the coma and I cannot' story. Land on household signal, sound, or wind-down.",
    [
        "they fell asleep like they left the planet",
        "they are gone in 40 seconds",
        "they dropped into the coma and I was the witness",
        "I can hear someone else successfully leaving",
        "they breathe like they already arrived in the not-here",
        "why can they disappear in one minute",
        "the person next to me already left the building",
        "they look peaceful like people look when they are not reachable",
        "I am watching someone sleep like I am watching a departure",
        "their night started on time and mine refused the exit",
        "they snore like they paid in full to be gone",
        "I get the leftover quiet after they vanish",
        "why is their body so sure it is safe to go",
        "the other pillow is already a finished disappearance",
        "I am the only one still in the day",
        "they rolled over and that was the whole exit",
        "someone in this bed is off the clock of being a person",
        "I whisper and they are already not here",
        "their face forgot the day first",
        "I am doing night next to a person who already did the leaving",
        "why do they get the easy version of going under",
        "they are heavy and I am hovering at the edge of the hole",
        "I count their breaths like that will teach me to leave",
        "the house has one sleeper and one witness of the rumor",
        "they got the dark and I got the dark plus homework",
        "I am jealous of a jaw that agreed to go",
        "they left me the lamp side of a night they abandoned",
        "why is their off-switch in the room",
        "I can feel them being elsewhere",
        "they won the night without trying to stay",
        "I am still introducing myself to the pillow",
        "their morning will make more sense because they completed the leaving",
        "I share a blanket with a finished person",
        "they are out and I am doing quality control on being out",
        "someone else made going away look optional to struggle with",
        "I get their warmth and not their ticket out",
        "they are a closed tab",
        "why does their night not need a reason to end",
        "I am the late show in a room that already ended",
        "they sleep like the comments say sleep works",
    ],
)

fam(
    "12-bed-is-a-hole",
    "False lead",
    "The bed is a hole. The couch is how I stay.",
    "Sleeping on the couch and waking in bed is a cue problem, not a portal. "
    "Unsell the 'official bed will take me' rumor. Land on screens, close-the-day, room setup.",
    [
        "the bed is a hole",
        "the couch is how I stay in my life",
        "I can sleep on the couch and not in the bed because the bed is the real leaving",
        "I get sleepy in the wrong room where it does not count as disappearing",
        "I was gone in the chair and born again under the sheet",
        "the couch holds me. the bed asks me to go away.",
        "I can sleep in cars and not in my own expensive dark",
        "I nod off at 9 in the living room and debut at 11 in the official coma",
        "the bed is where I remember I have a life so I cannot leave",
        "I can almost sleep sitting up like a coward who will not go under",
        "the sofa takes me. the mattress files me missing.",
        "I get heavy near a screen and light near a pillow that wants all of me",
        "I can sleep at other people's houses like a traitor to my hole",
        "hotels work and my bedroom does a presentation about going",
        "I fall asleep in the glow and wake up in the correct place angry I was moved",
        "the recliner is dishonest and it does not call it a night",
        "I can sleep through a movie and not through a plan to disappear",
        "my body trusts the couch's accidental night",
        "the bed is too intentional. it is a procedure.",
        "I get the wave on the floor and lose it in the sheets",
        "I can sleep on a plane with a stranger's elbow and not in my designed cave",
        "my own pillow is the one that turns the lights on so I will not go",
        "I doze in daylight like it does not count so I allow it",
        "the guest room would not know I am supposed to vanish",
        "I can sleep after the day collapses and not after I announce I will leave",
        "the car ride home had the sleep the bed wanted to steal",
        "I get pulled under by a boring meeting and pushed up by a quiet mattress",
        "the couch is a loophole in the coma",
        "I can sleep in a hoodie on the sofa like a person with no appointment to be gone",
        "the bed smells like trying to go under",
        "I was out during the ad break and awake for my own official wind-down",
        "I can sleep with a light on in the wrong room",
        "my body likes sleep as a side effect, not as a project",
        "the official night is the one I fail because it is named",
        "I can nap in a patch of sun like a cat and not in a designed cave",
        "the mattress is a stage for leaving. the couch is a ditch.",
        "I get sleepy putting a child down and then I become the adult who will not go",
        "I lose the sleepy when I decide it is time to disappear",
        "I can sleep through noise that is not the ritual",
        "the correct pillow is the problem because it is the door",
    ],
)

fam(
    "13-night-mind-trap",
    "False lead",
    "The second I lie down I leave my body and start a meeting.",
    "A loud mind at lights-out is not proof you never sleep, and not a second life you are trapped in. "
    "Unsell 'I never actually go.' Land on how-to-end-the-workday-from-home.",
    [
        "I close my eyes and start a meeting",
        "I lie down and my brain opens the laptop so I cannot leave",
        "the second my head lands, the day clocks back in",
        "I go horizontal and become management of a life I am trying to exit",
        "bed is where I write the email I will not send instead of going under",
        "I start the performance review of my own afternoon",
        "lying down is my office hours so sleep cannot clock me out",
        "I put my head down and pick up tomorrow",
        "the pillow is a desk",
        "I replay a conversation with better lines until morning",
        "I do strategy in the dark like that keeps me here",
        "I close the day and it files an appeal so I do not disappear",
        "my best ideas arrive when I am supposed to be gone",
        "I become employed at the exact moment I try to leave",
        "I hold still and my mind paces the room I was meant to exit",
        "I go to bed as if it were a second shift",
        "I start listing people I forgot so I have a reason to stay",
        "the dark is a whiteboard",
        "I lie there composing a life I already lived today",
        "I punch out and my brain punches in for unpaid overtime",
        "I start fixing a problem that is not due until Thursday",
        "I get brilliant at 12:20 about a sink",
        "I run the whole workday again with comments",
        "I become the most available I have been all day, to my own head",
        "I close my eyes and open the shared doc",
        "I do career thoughts like a hobby at 1am",
        "I lie down and remember every unfinished tab",
        "I start a presentation for an audience of ceiling",
        "I get sudden competence when it cannot be used",
        "I put the body to bed and leave the job running so I never go",
        "I negotiate a conversation that already ended",
        "I do inventory of my own competence in the worst lighting",
        "I go still and the to-do list stands up",
        "I start teaching a class nobody enrolled in",
        "I lie there being helpful to a day that is over",
        "I become a project manager of nothing",
        "I close my eyes and my calendar breathes",
        "I do the meeting I avoided, perfectly, too late",
        "I clock into a company that is just me and a pillow",
        "I start work because the house finally got quiet enough to think, so I will not leave",
    ],
)

fam(
    "14-object-kept-me",
    "False lead",
    "The 2pm coffee is the only thing that kept me from staying under.",
    "Caffeine can linger. It does not 'save you from a coma.' Unsell the life-support rumor. "
    "Land on coffee-timing-that-actually-matters. Same for wine, screens, overheads — leftovers, not spells.",
    [
        "the 2pm coffee is the only thing that kept me from staying under",
        "the laptop is closed and the meeting is the only proof I am still here",
        "that glass of wine is how I got closer to the hole",
        "the phone is face down and still holding me in the day",
        "the overhead light from 8pm is still in my skull so I cannot leave",
        "I can feel the salty dinner in my eyelids like I never went",
        "the unread email is on the nightstand in my chest",
        "that last episode left the TV in my head so I did not fully go",
        "the streetlight is a tiny day that would not let me disappear",
        "my water glass is empty and my mouth is dry like I ran from the night",
        "I brought the kitchen brightness into the bed and called it safety",
        "that second coffee had a longer shift than I did",
        "the blue from the bathroom night-light is a tiny life support",
        "my watch is charging and judging the leaving",
        "I left the tab open in my brain so I would not go under",
        "the takeout fullness stayed up to keep me here",
        "the fan is on and my thoughts are still unsynced with being gone",
        "I can hear the dishwasher finishing a day I did not finish",
        "the lamp I loved at 9 is too much at 11 if I am supposed to leave",
        "my socks are off and my feet are still at the desk",
        "the calendar notification found me under the blanket",
        "that protein bar at 10pm is doing cardio in a night I wanted empty",
        "I put the book down and the sentence kept me from the hole",
        "the ice water at 9 made my body think it was daytime sport",
        "my glasses are on the table and my eyes are still working the shift",
        "the playlist ended and I did not, so I never left",
        "that spicy thing is visiting me at 2 like a guard",
        "the laundry pile is a to-do list with arms",
        "I silenced the phone and it got louder in my thumb",
        "the candle is out and the vanilla is still hosting",
        "my ring light from a late call left a weather in the room",
        "the backpack by the door is already tomorrow refusing the night",
        "I turned the thermostat and my skin did not get the memo to go",
        "that chocolate was a small morning at midnight",
        "the keys in the bowl are the only thing that landed",
        "the hoodie I wore all day is still on my nervous system",
        "I used the phone as an alarm so the day never fully clocked out",
        "the mint is not covering the wine that walked me closer to gone",
        "I charged the watch next to my head so something would witness me",
        "the 2pm coffee is still in my eyes and I am calling it survival",
    ],
)

fam(
    "15-morning-still-under",
    "False lead",
    "Morning is acting like I came back. I did not.",
    "A used-up morning is not proof you stayed in a night-state. Unsell 'I never returned.' "
    "Land on morning light, then one evening variable. Not a verdict.",
    [
        "morning is acting like I came back. I did not.",
        "morning is acting like I rested",
        "the day started on a story that I returned",
        "daylight walked in like the night had been simple",
        "I woke up and the morning had already decided I was fine",
        "morning arrived like a bill for a night I am told I completed",
        "the sun was unreasonably sure I was here",
        "I woke up already apologizing for a night that counts as rest",
        "the kitchen is too bright for someone who just got extracted",
        "I woke up used and the morning said new",
        "morning feels like a continuation they will call a start",
        "I woke up and the to-do list had slept better than I did",
        "the morning is crisp and I am crumpled and I will still say hi",
        "daylight is a group project that assumed I made it back",
        "the first coffee is a rescue I have to call a habit",
        "morning is performing and I am still backstage of a finished night",
        "I stepped into a morning that did not wait for my evidence",
        "I woke up and my face had already commuted",
        "I am late to a morning that just started and already filed me as rested",
        "I woke up already late inside a day that insists I began on time",
        "morning found me mid-sentence of a night it closed",
        "I opened my eyes and the day had a head start it will not admit",
        "the day started without asking if I had finished coming back",
        "I sat up and owed three things before I was allowed to be tired",
        "I woke into a day that felt pre-owned",
        "the light is here and I am not assembled and the light does not care",
        "I lost the first hour before I stood and the calendar still starts at 9",
        "I opened my eyes and needed a buffer I am not supposed to need",
        "I woke up and my first thought was already a reply",
        "I came into the day sideways and called it normal",
        "I woke up missing a runway I will pretend I had",
        "I woke up already in the hallway of a day that sold me as ready",
        "I woke up with no on-ramp and a morning that has a schedule",
        "the day is a train I am jogging beside while it announces I boarded",
        "morning stole the soft hour and left me the sharp one labeled rest",
        "I woke up in progress of a reset I did not get",
        "the alarm was the second rude thing. the first was being told I slept.",
        "I woke up and needed the night to have been longer and I will say it was fine",
        "morning is a room I entered without shoes and everyone is dressed",
        "I woke up already spent on a day that has not charged me yet",
    ],
)

fam(
    "16-effort-spell",
    "False lead",
    "I did the routine so I would go under. It did not take me. So the routine is fake.",
    "A wind-down that does not knock you out is not proof the whole method is a lie, and not proof you will never sleep. "
    "Unsell 'if I don't vanish the advice is a scam.' Then one smaller tonight move.",
    [
        "I did the routine so I would go under. it did not take me.",
        "I dimmed the lights and I stayed bright so the night is fake",
        "I put the phone away and my thumb kept twitching like I refused the coma",
        "I drank the water and woke up dry anyway so rest is a rumor",
        "I stretched and my jaw undid it",
        "I wrote tomorrow's list and then I wrote it again in the dark",
        "I took the walk and the day followed me home so I could not leave",
        "I showered like that was a border and I stayed on this side",
        "I did the tea and the tea was just warm",
        "I read the boring page and I still invented a plot",
        "I laid out tomorrow's clothes like a bribe to the night",
        "I closed every tab and opened a better one behind my eyes",
        "I did the breathing and I counted the breathing so I never left",
        "I made the room cold and my thoughts ran to stay warm",
        "I put on the quiet show and I analyzed the quiet show",
        "I did not snack and my stomach held a meeting anyway",
        "I brushed my teeth like a closing ceremony for a person who did not close",
        "I did the whole wind-down and it was just chores at night",
        "I left the phone in the kitchen and my brain went to get it",
        "I did the lamps and not the leaving",
        "I tried the earlier bedtime and met a longer hallway",
        "I did not drink after 6 and 2pm still found me",
        "I washed my face like I could rinse the day off",
        "I did the stretch on the floor and stood up still at work",
        "I set the alarm with hope like that is a method for returning",
        "I did the journal line and then I narrated the journal line",
        "I tried no ceiling light and my laptop became the sun",
        "I did everything they tell you in the order they tell you",
        "I prepared a perfect night for a person who did not arrive to be gone",
        "I tried being good and being good was just more tasks",
        "I stacked the right objects and missed the off-switch",
        "I did the socks, the water, the book, the dark",
        "I tried less caffeine and more disappointment",
        "I earned the night and the night stayed unpaid",
        "I did the ritual so hard it became another job",
        "I tried to deserve disappearing",
        "I did the responsible evening and the irresponsible mind",
        "I put effort in the first hour and got taxed on the rest",
        "I tried so correctly that I could not get stupid enough to go",
        "I did the work of sleeping and forgot the sleeping",
    ],
)

fam(
    "17-identity-used-to-go",
    "False lead",
    "I used to fall asleep in cars. Now I cannot leave at all.",
    "A change in how easy sleep feels is not proof you lost the ability to wake, or to sleep. "
    "Unsell 'I am permanently stuck on this side.' Then one current-night move, not a personality verdict.",
    [
        "I used to fall asleep in cars",
        "I used to be a person who could leave",
        "I am not a night person and I am still awake like I failed the coma",
        "I used to drop at 10 like a stone into the hole",
        "I sleep like someone I would give advice to and not take",
        "I used to trust beds to take me",
        "I am a morning person trapped in a 1am body that will not go",
        "I used to nap on trains like it was nothing",
        "I do not recognize the person who negotiates with pillows",
        "I used to sleep through storms",
        "I am supposed to be the one who is good at disappearing",
        "I used to blink and it was morning",
        "I sleep like a guest in my own night",
        "I used to laugh at people who had a routine",
        "I am not the sleeper in any story about me",
        "I used to pass out after dinner",
        "I became someone who performs lying down",
        "I used to need 20 minutes. I now need a project plan to leave.",
        "I am a competent adult until the lights go off",
        "I used to sleep at other people's houses with no fear of not returning",
        "I do not know when I stopped being easy to take",
        "I used to wake up in the same century I fell asleep in",
        "I am the friend who used to sleep anywhere",
        "I used to close my eyes as a decision",
        "I sleep like I am being graded on the leaving",
        "I used to be bored into sleep",
        "I am a person with a bedtime and no sleep time",
        "I used to get heavy without asking",
        "I do not remember the last easy night I did not photograph in my head",
        "I used to think sleep was what happened after the day",
        "I am trying to be the kind of person who just goes to bed",
        "I used to drool on planes",
        "I sleep like an impersonation of rest",
        "I used to not notice the clock",
        "I am someone who now has opinions about pillows",
        "I used to fall asleep talking",
        "I do not feel like the me who could do nights",
        "I used to wake hungry, not hunted",
        "I am a daytime personality with a nighttime glitch",
        "I used to think I would always be able to go and come back",
    ],
)

fam(
    "18-body-receipt-fight",
    "False lead",
    "My jaw is sore so I was not asleep. I was fighting being gone.",
    "A sore jaw, dry mouth, or stiff neck is a body receipt — not proof you never slept, and not proof you were in another state. "
    "Unsell the 'I faked the whole night' rumor. Then one practical evening note. Bigger patterns go to professional support.",
    [
        "my jaw is sore so I was not asleep. I was fighting being gone.",
        "my jaw is sore and I was 'asleep'",
        "my neck paid for a night I do not remember so it was not rest",
        "I woke up and my teeth had a job",
        "my tongue is dry like I ran from the night",
        "my shoulders are up around a sleep I was supposed to drop",
        "I have a pillow crease that looks like a scar from trying to stay",
        "my hips ache like I held a position in a meeting I never left",
        "I woke with a hand numb from a night of gripping the day",
        "my throat is scratchy from a mouth that would not close because I would not go",
        "I have a knot under my shoulder blade named 2am",
        "my calves are tight like I stood in my sleep",
        "I woke and my low back filed that I never left",
        "my lips are cracked from air I breathed too long on this side",
        "I have a sore spot on my scalp from the same turn",
        "my wrists hurt from a phone I already put down",
        "I woke with my eyebrows still raised",
        "my nose is stuffed from a pillow height I keep choosing",
        "I have morning tightness that feels like leftover effort",
        "my ears are ringing in a quiet room",
        "I woke and my stomach was loud in a night kitchen way",
        "my knees feel older than the date",
        "I have a bite on the inside of my cheek I do not remember placing",
        "my collarbone is tender from a side I would not leave",
        "I woke with my toes clenched",
        "my sinuses did a whole weather system",
        "I have a crick that is just the night in one line",
        "my chest feels braced like I was ready not to go",
        "I woke and my ankles were hot",
        "my hairline is damp and the room is not",
        "I have a numb lip from sleeping like a statue who refused",
        "my eye socket aches in a way that feels like squinting at dreams",
        "I woke with my tongue stuck to a dry roof",
        "my right shoulder is the one that stayed employed",
        "I have fingerprint marks in my palm from my own nails",
        "my hips click like I stored the day in the joints",
        "I woke and my face muscles were tired of being a face",
        "my throat clicked when I swallowed the first time",
        "I have a bruise-feeling on my cheek from a seam",
        "my whole left side is the receipt that I never went under",
    ],
)

fam(
    "19-one-variable-ruined",
    "False lead",
    "I only moved my bedtime and now I cannot wake.",
    "One change can slide a week. It does not trap you in a night-state forever. "
    "Unsell 'I broke myself for good.' Then name the variable without turning it into a curse.",
    [
        "I only moved my bedtime and now I cannot wake",
        "I only had the coffee later and the night kept me",
        "I only left the big light on until 10 and I could not leave",
        "I only watched one more episode and I lost the exit",
        "I only skipped the walk and the day followed me into the hole",
        "I only slept in once and the week would not return me",
        "I only moved the phone to the bed and the day never clocked out",
        "I only had the late salty thing and my face stayed in the night",
        "I only took the nap that felt harmless and I tested the coma",
        "I only closed the laptop in the same room I sleep",
        "I only changed the pillow and now I have a neck story",
        "I only drank the wine because the day was long and I went closer",
        "I only checked the score first and let it write the official going",
        "I only sat on the couch to rest my eyes and I dropped",
        "I only answered one email after 9 and I stayed employed",
        "I only kept the hallway light for the kid and the house never went under",
        "I only made the room warmer because I was sick of being brave",
        "I only skipped morning light because I was late and I never fully returned",
        "I only used the phone as an alarm again",
        "I only had water and still woke up like I had been talking",
        "I only changed jobs to work from home and the day never ended",
        "I only started sleeping next to someone who is good at leaving",
        "I only bought blackout curtains and discovered my mind",
        "I only stopped the nightly show and heard the house",
        "I only added a tracker and started performing the disappearance",
        "I only moved cities and the dark arrives wrong",
        "I only had a baby and now the night has shifts",
        "I only started caring and that was the variable",
        "I only went to bed proud of being early and I overshot",
        "I only opened the shade at 5 because a truck did",
        "I only said I would rest and turned it into a project",
        "I only switched to the other side of the bed",
        "I only had a quiet Sunday and it made Monday violent",
        "I only used the guest blanket",
        "I only thought about tomorrow on purpose so I would not go",
        "I only charged the watch next to my head",
        "I only ate later because the house finally sat down",
        "I only skipped the wind-down because I was already late to leaving",
        "I only changed one lamp",
        "I only decided tonight mattered and then it would not start",
    ],
)

fam(
    "20-second-wake-kept",
    "False lead",
    "The second wake is the one that almost does not include me.",
    "Waking twice is common. The second wake is not a failed return from a coma. "
    "Unsell the 'I used up my one wake.' Then coffee, light, or what to do with the clock — not fate.",
    [
        "the first wake I can ignore. the second one owns me.",
        "the second wake is the hour I almost do not get a third chance",
        "I came back the second time and stayed because I was afraid to go again",
        "the second wake is the real night",
        "I can forgive 2am. 3:20 keeps the keys.",
        "I woke, I almost made it, I woke wiser and sadder",
        "the second time I opened my eyes I was employed",
        "I get one free return. the next one charges.",
        "the second wake brings a list so I will not disappear again",
        "I rolled back once and the second roll failed",
        "after the second wake I start living in the dark on purpose",
        "I can fall back from the first. the second wants a conversation.",
        "the encore is worse than the show",
        "I woke twice and the second one remembered my name",
        "the first wake is a glitch. the second is a decision I did not make.",
        "I lost the night on the replay",
        "the second wake turns the bedroom into a waiting room",
        "I can pretend the first one did not happen",
        "after the second I start planning breakfast like a hostage",
        "the second wake is when I check the time and lose",
        "I came up twice and the water was colder",
        "the first return I was still a sleeper. the second I was a person.",
        "I can drop after one interruption. two makes a plot.",
        "the second wake invites the day in street clothes",
        "I woke, I bargained, I woke and the bargain was over",
        "the second one is when my jaw reports",
        "I get a draft night and then a final night that is just thinking",
        "the second wake has opinions about tomorrow",
        "I can love the first darkness. the second darkness is administrative.",
        "after two wakes I am just lying in a room",
        "the second wake is a roommate turning the light on in my head",
        "I went back and the bed had changed sides",
        "the first wake is noise. the second is me refusing to go.",
        "I can close the first tab. the second tab is the browser.",
        "the second wake starts the unofficial morning at 4",
        "I returned twice and unpacked",
        "the second time I was too awake to be innocent",
        "I can float after one. two sinks me into the mattress as a thinker.",
        "the second wake is when I become available to every leftover",
        "I woke again and this time I stayed to keep watch so I would not be taken",
    ],
)

fam(
    "21-brochure-lied",
    "False lead",
    "Nobody told me sleep could look like not coming back.",
    "The missing-manual feeling is real. It is not proof that adults were sold a coma. "
    "Unsell 'they lied, sleep is dangerous.' Then one boring true thing and one tonight move.",
    [
        "nobody told me sleep could look like not coming back",
        "nobody told me mornings could look like this",
        "why did no one say sleep can make you look worse",
        "I thought the tired face was for people who did not try",
        "nobody mentioned the 3am shift in a normal life",
        "why is this not in the brochure of being a person",
        "I thought adults just went to bed and came back new",
        "nobody said the first hour of morning might be a negotiation",
        "I was told to get 8 hours like that was a button into the hole",
        "why did they talk about nights like they were simple math",
        "nobody warned me I would miss being bored at 10",
        "I thought red eyes meant I had a story. I only had a pillow.",
        "nobody said you can do everything right and still meet 3:07",
        "why is the official advice written for a different animal",
        "I thought sleep was what happened if you were tired enough",
        "nobody mentioned the night mind getting promoted",
        "I was not told the couch would become a rival to the hole",
        "why did they skip the part where you do not want to sleep",
        "nobody said your face can keep a night you forgot",
        "I thought morning was a reset and it is a leftover",
        "nobody told me quiet can be the thing that wakes you",
        "I was sold a routine like it was a key and it is a chore list",
        "why does every guide assume I want to go to bed",
        "nobody said the tracker would become a third person in the room",
        "I thought darkness was enough infrastructure",
        "nobody mentioned waking up already behind a day that just started",
        "I was not told Saturday morning could ruin Sunday night",
        "why did they not say the hours can bounce",
        "nobody warned me I would become someone with a pillow opinion",
        "I thought kids were the only reason nights get weird",
        "nobody said you can be sleepy in the wrong room on purpose",
        "I was not prepared for the politics of one lamp",
        "why is the missing chapter the one about not wanting the night to end",
        "nobody told me my jaw would moonlight",
        "I thought being tired was the ticket and I keep losing it at the door",
        "nobody said you can wake up thirsty from a night of nothing",
        "I was not told the first thought could be a meeting",
        "why did they make sleep sound like manners",
        "nobody mentioned the specific grief of almost",
        "I thought I would always know how to do this",
    ],
)

fam(
    "22-unsaid-want-stay",
    "False lead",
    "I do not want to sleep. I want to stay so I cannot be taken.",
    "Wanting the quiet house is real. It is not proof that sleep is a theft you must refuse. "
    "Unsell 'staying up is how I survive.' Then name the want, then one smaller close to the day.",
    [
        "I do not want to sleep I want the house to stay mine",
        "I do not want to sleep. I want to stay so I cannot be taken.",
        "I am protecting the only quiet I get",
        "I am not tired of being awake I am tired of the performance of going to bed",
        "I want one more hour that belongs to nobody",
        "I stay up because it is the first time today no one needs me",
        "I am not chasing rest I am chasing a room with no tasks",
        "I want the lamp more than I want the morning",
        "I keep the night because daytime is rented",
        "I am awake on purpose and still mad about it",
        "I want to be left by the day, not tucked in by a routine",
        "I stay up to feel like the main character of a nothing evening",
        "I am not avoiding sleep I am extending the only unlocked door",
        "I want silence that I chose",
        "I linger because tomorrow starts the asking again",
        "I am greedy for empty time and I pay in morning face",
        "I want to sit in the dark without it being a method",
        "I stay awake to keep a little of the day I did not get",
        "I am using night as a spare room",
        "I want privacy more than I want 8 hours of being gone",
        "I refuse the bedtime because it feels like someone else's idea of good",
        "I am not wired I am unwilling to close the shop",
        "I want the house at 11 more than the person at 7",
        "I stay up to hear the fridge and call it peace",
        "I am stealing tonight from tomorrow and I know",
        "I want to finish being a person before I become a sleeper",
        "I keep my eyes open like that keeps the apartment mine",
        "I am not scared of tomorrow I am not done with today",
        "I want a night that is not a prelude to leaving",
        "I stay up because sleep feels like losing the last room",
        "I am awake because this is the only unsupervised hour",
        "I want to waste time that is actually mine",
        "I will not go to bed until I feel like I lived a little",
        "I am holding the quiet hostage",
        "I want rest without surrender",
        "I stay up to feel unneeded",
        "I am not procrastinating sleep I am rationing solitude",
        "I want the night to last until I feel caught up on being alone",
        "I keep watch because daytime is a group project",
        "I want sleep later, after I have had a life for 20 minutes",
    ],
)

fam(
    "23-almost-gone-for-good",
    "False lead",
    "I was almost gone and that felt like the start of not coming back.",
    "The 'almost asleep' edge is an ordinary open loop, not the lip of a coma. "
    "Unsell 'if I cross I will not return.' Then one smaller off-ramp, not a panic.",
    [
        "I was almost gone and then my jaw clenched",
        "I was almost gone and that felt like the start of not coming back",
        "I was almost asleep and then a thought sat down",
        "I hit the edge and the edge moved",
        "I was that close and my phone lit the ceiling",
        "I almost made it and then I swallowed",
        "I was dropping and my leg kicked me back",
        "almost out. then the list.",
        "I had the heavy body and the loud head",
        "I was halfway under and someone said my name in my head",
        "I almost crossed and my mouth got dry",
        "I was this close to the first real stretch",
        "I felt the slide and then I felt the floor",
        "almost asleep is a country I live in",
        "I had one foot in and the day pulled the other",
        "I was leaving and my shoulder hurt so I came back",
        "I almost let go and then I checked if I let go",
        "I was on the first step down and the meeting started",
        "I nearly vanished and then I remembered tomorrow",
        "I was soft and then I was solving",
        "almost gone, then a swallow, then a whole night",
        "I had the wave and I surfed it back to 11:59",
        "I was disappearing and my ear noticed the fridge",
        "I almost trusted the dark",
        "I was under the first blanket of it and then I planned breakfast",
        "I got to the doorway of sleep and knocked",
        "I was slipping and I grabbed the thought like a rail",
        "almost. then I rolled over and started again.",
        "I had 20 seconds of nobody home and then I was home",
        "I was about to drop the day and I picked it up to look",
        "I nearly spent the night and I refunded myself at 1",
        "I was this near to not caring and then I cared",
        "I felt sleep in my hands and I opened them",
        "I was going and my nose got itchy like a joke",
        "almost out, then I wondered if I was almost out",
        "I had the first blank and I wrote on it",
        "I was sinking and I sat up in my mind",
        "I nearly made a night of it",
        "I was at the lip and I narrated the lip",
        "I was gone enough to miss it when I came back",
    ],
)

fam(
    "24-room-perfect-trap",
    "False lead",
    "The room is perfect so if I do not go I am the problem. If I do go I might not come back.",
    "A quiet dark room is a cue, not a trap and not a test of your character. "
    "Unsell both rumors. Then one environment move from the light / sound / temp guides.",
    [
        "the room is quiet and I am not",
        "the dark is doing everything and I am still on",
        "this bedroom looks like night and I look like noon",
        "the pillow is ready and I am still employed",
        "cool air, warm brain",
        "the curtains closed and my thoughts opened",
        "I built a cave and brought a stadium in",
        "the bed is made for a person who arrived to leave",
        "silence is loud when I am the only noise",
        "the lamp is off and the day is still projected on the wall of my head",
        "this room cost money to be this dim and I wasted it",
        "the sheets are cold in a way that should work",
        "I did the room and not the night",
        "blackout curtains, floodlight mind",
        "the fan is steady and I am not",
        "I made the perfect conditions for someone else to disappear",
        "the air smells like laundry and I smell like a deadline",
        "this is a sleep room hosting a work meeting",
        "the mattress is quiet. I creak.",
        "I dimmed the world and my pulse did not dim",
        "the window is doing night correctly",
        "I am the only lamp left on",
        "soft pillow, sharp list",
        "the room whispered and I answered in paragraphs",
        "I turned the house down and left myself at full volume",
        "this darkness is rented by a brain that did not sign",
        "the corner is shadows and I am a spreadsheet",
        "I can hear how empty the room is",
        "the bed knows what it is. I am still deciding.",
        "nice room. wrong tenant.",
        "I bought quiet and it does not fit",
        "the nightstand looks peaceful without me",
        "I am too awake for this wallpaper",
        "the rug, the lamp, the whole set, and then me",
        "the room is a closed shop and I am still shopping",
        "I matched the temperature and missed the person",
        "this is what night looks like from the outside of my body",
        "the walls are doing nothing and that should be enough to take me",
        "I staged a bedroom and forgot to exit the day",
        "the dark is available and I am booked",
    ],
)

fam(
    "25-proof-cold-lead",
    "False lead",
    "This is my face after a full night. This is what almost not coming back looks like.",
    "A harsh bathroom still is evidence of a morning, not of a coma. "
    "Unsell the caption the screenshot wants. Then one real variable. Never let the still travel as a diagnosis.",
    [
        "this is my face after a full night",
        "this is what almost not coming back looks like",
        "this is the eye that slept",
        "this is what 8 hours looked like on me",
        "this is the crease I did not ask for",
        "this is morning without the story",
        "this is the pillow side of a night they will call rest",
        "this is a rested person apparently",
        "this is the red they said sleep would clear",
        "this is my mouth after I was supposed to be gone",
        "this is the hair of someone who fought a sheet",
        "this is 3:07's leftover",
        "this is the swelling I earned by lying still",
        "this is my Tuesday face on a night I behaved",
        "this is what the watch called great",
        "this is not a late night. this is a night.",
        "this is the look I get for doing it right",
        "this is my skin after darkness",
        "this is the jaw that would not quit",
        "this is a bathroom mirror, no filter, no lesson yet",
        "this is the eye that worked the night shift",
        "this is after I finally slept",
        "this is the unedited morning",
        "this is what I get for staying in bed",
        "this is my face when the hours were legal",
        "this is not glamorous tired. this is receipt tired.",
        "this is the puffy one",
        "this is me meeting daylight",
        "this is the night still sitting on my lids",
        "this is a full sleep and a half face",
        "this is the proof I do not need a caption for",
        "this is after the routine",
        "this is the opposite of a glow",
        "this is my own night in the harsh bulb",
        "this is what I look like when I do not have a story",
        "this is the morning I paid for",
        "this is sleep on my face, not in it",
        "this is the still from a night with no plot",
        "this is me, post-dark",
        "this is why I asked why should I sleep",
    ],
)


def main() -> None:
    all_hooks: list[tuple[int, str, str, str, str, str]] = []
    n = 0
    for slug, mother, lead, unsell, hooks in FAMILIES:
        for h in hooks:
            n += 1
            all_hooks.append((n, slug, mother, lead, unsell, h))

    if n != 1000:
        raise SystemExit(f"expected 1000 hooks, got {n}")

    lowered = [h.lower().strip() for *_, h in all_hooks]
    if len(set(lowered)) != 1000:
        seen: set[str] = set()
        dups = []
        for x in lowered:
            if x in seen:
                dups.append(x)
            seen.add(x)
        raise SystemExit(f"duplicate hooks: {dups[:20]}")

    bad = [(i, h) for i, *_, h in all_hooks if BANNED.search(h)]
    if bad:
        raise SystemExit(f"banned language: {bad[:10]}")

    lines = [
        "# SleepAlb — 1,000 false-lead hooks",
        "",
        "The hook starts **almost wrong**. The story unsells it. The info lives in the body.",
        "",
        "Example: `sleeping can put you in a coma` → it cannot. Sleep is not a coma. Then the mix-up. Then one tonight move.",
        "",
        "These lines are **leads only**. Do not post a screenshot of the first frame as a fact. "
        "Each family names the unsell the story owes.",
        "",
        "Craft: [`02-gaslight-texture.md`](./02-gaslight-texture.md). "
        "How a post ships: [`00-sleepalb-direction-strategy.md`](./00-sleepalb-direction-strategy.md).",
        "",
        "Do not run L0 critic on this file. Hooks are not captions.",
        "",
        f"**Count:** {n} unique lines. 25 families × 40.",
        "",
    ]

    current = None
    for i, slug, mother, lead, unsell, h in all_hooks:
        if slug != current:
            current = slug
            title = slug.split("-", 1)[1].replace("-", " / ")
            lines += [
                "---",
                "",
                f"## {slug} — {title}",
                "",
                f"**Lead type:** {lead}  ",
                f"**Mother:** {mother}  ",
                f"**Story must unsell:** {unsell}",
                "",
            ]
        lines.append(f"{i}. {h}")
        lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {n} hooks → {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()



