#!/usr/bin/env python3
"""Build SleepAlb 1000-hook bank from authored pattern families."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "content/02_CONTENT/directions/1000-hooks.md"

# Hard-list adjacent words that must not appear in an opener.
BANNED = re.compile(
    r"\b(cure|cures|treat|treats|heal|heals|prevent|prevents|preventing|"
    r"remedy|remedies|miracle|diagnos\w*|guarantee\w*|clinically|melatonin|"
    r"insomnia|apnea|anxiety|depression|adhd|therapy|disorder|prescription|"
    r"supplement|treatment|physician|fda)\b",
    re.I,
)

FAMILIES: list[tuple[str, str, str, list[str]]] = []


def fam(slug: str, mother: str, gap: str, hooks: list[str]) -> None:
    if len(hooks) != 40:
        raise SystemExit(f"{slug}: expected 40 hooks, got {len(hooks)}")
    FAMILIES.append((slug, mother, gap, hooks))


fam(
    "01-dare-why",
    "Forbidden question",
    "Is tonight even worth it.",
    [
        "why should I sleep",
        "why should I sleep if I just lie there",
        "why should I sleep when I wake up tired anyway",
        "why should I go to bed at 10",
        "why should I sleep 8 hours",
        "why should I sleep if tomorrow is already a mess",
        "why should I sleep instead of finishing this",
        "why should I sleep when my brain just started",
        "why should I sleep if I napped at 4",
        "why should I sleep on a Sunday night",
        "why should I sleep when the house is finally quiet",
        "why should I sleep if I feel more alive at 11",
        "why should I close my eyes right now",
        "why should I sleep when I already wasted the day",
        "why should I sleep if I can rest on the couch",
        "why should I sleep before I feel ready",
        "why should I sleep on a work night",
        "why should I sleep if I sleep in on weekends",
        "why should I sleep when nobody else in this house is",
        "why should I sleep if I have one more episode",
        "why should I sleep when my list is still open",
        "why should I sleep if I am not even sleepy",
        "why should I sleep after a day I barely used",
        "why should I sleep when I finally have time to think",
        "why should I sleep if morning me will still be tired",
        "why should I get in bed this early",
        "why should I sleep instead of scrolling",
        "why should I sleep when I just got comfortable out here",
        "why should I sleep if I already feel behind",
        "why should I sleep on nights like this",
        "do I even need to sleep tonight",
        "is sleep optional if I sit still",
        "why bother sleeping if I wake at 3",
        "why should I try when I already know I won't",
        "why should I sleep when coffee is still in me",
        "why should I sleep if I can just push through",
        "why should I sleep when the deadline is tomorrow",
        "why should I sleep if someone will wake me anyway",
        "why should I sleep after a night shift",
        "why should I sleep when staying up feels like control",
    ],
)

fam(
    "02-aftermath-face",
    "Information gap + proof",
    "Sleep should have cleared the face.",
    [
        "my eyes are red after sleep",
        "my eyes are redder after I slept",
        "I slept and my eyes look worse",
        "why are my eyes red if I just slept",
        "my eyes look like they skipped the night",
        "I closed my eyes for hours and they look angry",
        "sleep did something to my eyes",
        "my eyes are puffy like I argued with the pillow",
        "I woke up and my eyes were already tired",
        "why do my eyes look open after I shut them all night",
        "my eyelids are heavy and my eyes are loud",
        "I have sleep in my face and not in my eyes",
        "my eyes are dry and I was horizontal for 8 hours",
        "why is my first view of the morning my own red eyes",
        "I look like I cried and I only slept",
        "my under-eyes showed up to work before I did",
        "sleep left a stamp on my eyes",
        "I went to bed with a face and woke up with last night on it",
        "why do I look more tired in the bathroom than I felt in bed",
        "my eyes are bloodshot and my night was quiet",
        "I slept on my face and my face kept the receipt",
        "why are my eyes swollen if I didn't even use them",
        "my eyes look like a night shift I do not remember",
        "I finally slept and my eyes still look mid-scroll",
        "red eyes after a full night feels like a scam",
        "my lashes are stuck and I was supposed to be resting",
        "why does morning light make my eyes look guilty",
        "I hid in the dark and my eyes still look overworked",
        "my eyes are glassy and I just woke up",
        "someone slept. it was not my face.",
        "I can see the night in my eyelids",
        "why do my eyes look dehydrated after water and sleep",
        "my eyes are pink and I did the whole night",
        "I look allergic to my own pillow",
        "the first thing I see is how little my eyes recovered",
        "my eyes are tight like I squinted all night",
        "why is my eye crease deeper after rest",
        "I slept on my side and one eye looks like it stayed up",
        "my eyes are red and my mouth is dry and that was sleep",
        "I asked sleep to fix my face and it billed my eyes",
    ],
)

fam(
    "03-broken-hours",
    "Broken deal",
    "I paid in hours.",
    [
        "I slept 8 hours and I look worse",
        "I was in bed 9 hours and I got 5",
        "8 hours did not buy me a morning",
        "I paid a full night and woke up owing",
        "why did more hours make me heavier",
        "I collected 8 hours like it was a paycheck",
        "long night. short morning.",
        "I gave the bed a whole shift",
        "7 hours 42 minutes and still this face",
        "I stayed down and nothing stacked",
        "why is time in bed not the same as sleep",
        "I filled the night and emptied the morning",
        "8 hours in the dark and I still feel unspent",
        "I did the hours. the hours did not do me.",
        "a full night and a half-awake body",
        "I booked 8 hours and got a layover",
        "why do extra hours feel like extra weight",
        "I was horizontal long enough to be a different person",
        "the clock says I slept. I was there. I disagree.",
        "I put in overtime in bed",
        "9 hours later I still need a minute",
        "I slept the recommended amount of a stranger",
        "why does 6 hours some nights beat 8 hours these nights",
        "I stayed in bed like that would count",
        "a long lie-down is not a night",
        "I gave sleep my whole evening and it kept the change",
        "8 hours and I woke up mid-sentence",
        "I completed the night on paper",
        "why did the long night feel like a draft",
        "I stacked hours and woke up unbuilt",
        "full night, leftover body",
        "I met the number and missed the morning",
        "10 hours on Saturday still bounced",
        "I stayed under the blanket like it was a shift I could finish",
        "the hours happened. the rest did not show up.",
        "I was in that bed long enough to file a complaint",
        "8 hours later I am starting from behind",
        "I did not short the night and the night still shorted me",
        "why can I feel every hour I spent not sleeping",
        "I paid in dark and got a dim morning",
    ],
)

fam(
    "04-false-finish",
    "False finish",
    "I thought I made it.",
    [
        "I finally slept and my face is angry",
        "I finally slept and my eyes got worse",
        "I thought the night was over",
        "I made it to sleep and sleep sent me back",
        "I was out and then I was not",
        "I thought I won at 1am",
        "I crossed the line and the night moved it",
        "I fell asleep like that was the ending",
        "I got there and the night started a second episode",
        "I thought darkness meant I was done",
        "I finished the day and the day followed me in",
        "I closed my eyes like a door that latches",
        "I thought I left. I was only in the hallway.",
        "I slept enough to think I was safe",
        "I got the first sleep and lost the rest",
        "I thought the heavy feeling was the night arriving",
        "I dropped off and woke up still holding the day",
        "I finally got quiet and my jaw started working",
        "I thought 2am was the bottom",
        "I arrived in sleep and someone had already lived there",
        "I believed the first stretch",
        "I thought I used the night up",
        "I got under and the night stayed on top",
        "I finished my wind-down and my mind opened a new file",
        "I thought the last blink was the last blink",
        "I slept like a person who was going to stay slept",
        "I had a full first hour and then the night bounced",
        "I thought I negotiated a whole night",
        "I got through the hard part and the hard part had a second half",
        "I closed the laptop and opened a worse tab in my head",
        "I thought the couch sleep counted as the real one",
        "I made it to the bed and the bed was not the finish",
        "I thought morning would find me further along",
        "I fell into it and it spit me out at 3",
        "I called it a night and the night did not take the call",
        "I got the heavy eyes and not the rest",
        "I thought I was past the wired part",
        "I landed and then I was circling again",
        "I finally felt gone and my name was still on the night",
        "I thought sleep had accepted me",
    ],
)

fam(
    "05-clock-ghost",
    "Clock ghost",
    "This time owns me.",
    [
        "why is it always 3:07",
        "3:07 again",
        "I do not remember deciding to be awake at 5:47",
        "4:11 is not a time I chose",
        "why does 2:58 feel like a meeting",
        "it is 3 and I am already behind tomorrow",
        "2:14 and my brain clocked in",
        "why is 5:03 the hour that keeps me",
        "I wake at the same ugly minute",
        "3:40 and the night is a hallway",
        "why do I know 1:17 too well",
        "12:49 is when I start losing the argument",
        "it is 4 something and I am negotiating with a clock",
        "6:02 and I feel like I missed a night I was in",
        "why is 3am more honest than 11pm",
        "I open my eyes and the clock already knew",
        "2:33 is doing a bit at this point",
        "why is my body loyal to 3:10",
        "5:19 and I have not agreed to be a person yet",
        "the clock says 3 and my chest says work",
        "1:08 is too early to have a second night",
        "why do I wake 12 minutes before the alarm like I am competing",
        "4:44 feels personal",
        "I could draw 3:05 with my eyes closed",
        "2am is when the house is mine and I cannot use it",
        "why is 11:41 the last time I felt close",
        "3:21 and I start planning a day I will be too thin for",
        "the minute is specific and that is the insult",
        "5:55 and I lost the second half for nothing",
        "why does 6:08 feel later than 7",
        "I wake before the birds and after my chance",
        "3 on the dot like I set it",
        "why is 2:07 when my jaw reports for duty",
        "4am thoughts are just daytime thoughts with worse lighting",
        "I know this minute better than my own bedtime",
        "12:12 and I am still performing being awake",
        "why do I keep appointment with 3:16",
        "the clock is the only one consistent in this room",
        "5:41 and I have the whole disappointment of morning with none of the light",
        "I woke at a time that feels like a name",
    ],
)

fam(
    "06-almost",
    "Almost",
    "I was that close.",
    [
        "I was almost gone and then my jaw clenched",
        "I was almost asleep and then a thought sat down",
        "I hit the edge and the edge moved",
        "I was that close and my phone lit the ceiling",
        "I almost made it and then I swallowed",
        "I was dropping and my leg kicked me back",
        "almost out. then the list.",
        "I had the heavy body and the loud head",
        "I was halfway under and someone said my name in my head",
        "I almost crossed and my mouth got dry",
        "I was this close to the first real stretch",
        "I felt the slide and then I felt the floor",
        "almost asleep is a country I live in",
        "I had one foot in and the day pulled the other",
        "I was leaving and my shoulder hurt so I came back",
        "I almost let go and then I checked if I let go",
        "I was on the first step down and the meeting started",
        "I nearly vanished and then I remembered tomorrow",
        "I was soft and then I was solving",
        "almost gone, then a swallow, then a whole night",
        "I had the wave and I surfed it back to 11:59",
        "I was disappearing and my ear noticed the fridge",
        "I almost trusted the dark",
        "I was under the first blanket of it and then I planned breakfast",
        "I got to the doorway of sleep and knocked",
        "I was slipping and I grabbed the thought like a rail",
        "almost. then I rolled over and started again.",
        "I had 20 seconds of nobody home and then I was home",
        "I was about to drop the day and I picked it up to look",
        "I nearly spent the night and I refunded myself at 1",
        "I was this near to not caring and then I cared",
        "I felt sleep in my hands and I opened them",
        "I was going and my nose got itchy like a joke",
        "almost out, then I wondered if I was almost out",
        "I had the first blank and I wrote on it",
        "I was sinking and I sat up in my mind",
        "I nearly made a night of it",
        "I was at the lip and I narrated the lip",
        "I almost didn't notice myself and then I did",
        "I was gone enough to miss it when I came back",
    ],
)

fam(
    "07-object-leftover",
    "Object leftover",
    "The day is still in the room.",
    [
        "the 2pm coffee is still in my eyes",
        "the laptop is closed and the meeting is not",
        "that glass of wine is sleeping in my face",
        "the phone is face down and still talking",
        "my charger is doing more resting than I am",
        "the overhead light from 8pm is still in my skull",
        "I can feel the salty dinner in my eyelids",
        "the unread email is on the nightstand in my chest",
        "that last episode left the TV in my head",
        "the streetlight is in the room even with the curtain",
        "my water glass is empty and my mouth is not done being dry",
        "the hoodie I wore all day is still on my nervous system",
        "I brought the kitchen brightness into the bed",
        "that second coffee had a longer shift than I did",
        "the blue from the bathroom night-light is a tiny day",
        "my watch is charging and judging",
        "the novel has a plot and now so does 12:40",
        "I left the tab open in my brain",
        "the takeout container is gone and the fullness stayed up",
        "that mint is not covering the wine in my sleep",
        "the fan is on and my thoughts are still unsynced",
        "I can hear the dishwasher finishing a day I did not finish",
        "the lamp I loved at 9 is too much at 11",
        "my socks are off and my feet are still at the desk",
        "the calendar notification found me under the blanket",
        "that protein bar at 10pm is doing cardio",
        "the perfume I wore to feel like a person is still awake",
        "I put the book down and the sentence kept going",
        "the ice water at 9 made my body think it was daytime sport",
        "my glasses are on the table and my eyes are still working",
        "the playlist ended and I did not",
        "that spicy thing is visiting me at 2",
        "the laundry pile is a to-do list with arms",
        "I silenced the phone and it got louder in my thumb",
        "the candle is out and the vanilla is still hosting",
        "my ring light from a late call left a weather in the room",
        "the backpack by the door is already tomorrow",
        "I turned the thermostat and my skin did not get the memo",
        "that chocolate was a small morning at midnight",
        "the keys in the bowl are the only thing that landed",
    ],
)

fam(
    "08-someone-else",
    "Someone else can",
    "Their night worked.",
    [
        "they are gone in 40 seconds",
        "my partner is asleep and I am taking minutes",
        "they breathe like the day ended",
        "I can hear someone else succeeding at night",
        "they dropped into sleep like a dropped coat",
        "why can they do in one minute what I cannot do in one hour",
        "the person next to me already left",
        "they look peaceful and I look employed",
        "I am watching someone sleep like it is a skill I lost",
        "their night started on time",
        "they snore like they paid in full",
        "I get the leftover quiet after they vanish",
        "why is their body so sure",
        "they are on chapter sleep and I am still in the table of contents",
        "the other pillow is already a finished night",
        "I am the only one still in the day",
        "they rolled over and that was the whole story",
        "someone in this bed is off the clock",
        "I whisper and they are already not here",
        "their face forgot the day first",
        "I am doing night next to a person who already did it",
        "why do they get the easy version",
        "they are heavy and I am hovering",
        "I count their breaths like that will teach me",
        "the house has one sleeper and one witness",
        "they got the dark and I got the dark plus homework",
        "I am jealous of a jaw that unclenched",
        "they left me the lamp side of the night",
        "why is their off-switch in the room and mine is not",
        "I can feel them being elsewhere",
        "they won the night without trying",
        "I am still introducing myself to the pillow",
        "their morning will make more sense than mine",
        "I share a blanket with a finished person",
        "they are out and I am doing quality control on being out",
        "someone else made it look optional to struggle",
        "I get their warmth and not their sleep",
        "they are a closed tab",
        "why does their night not need a reason",
        "I am the late show in a room that already ended",
    ],
)

fam(
    "09-score-liar",
    "Score liar",
    "The number is in a better mood than I am.",
    [
        "my watch said I slept great",
        "92 and I still cannot see my own face",
        "my ring is in love with a night I do not remember",
        "the app celebrated and my eyes did not get the memo",
        "I got a badge for a night that felt like a draft",
        "my score is confident and I am not",
        "the graph is green and my mood is hallway lighting",
        "I woke up to a compliment from a bracelet",
        "why does the number think we are friends",
        "8 hours, 91, and a head like wet paper",
        "my watch slept better than I did",
        "the ring wants a high five",
        "I have data for a rest I did not meet",
        "the sleep stage pie chart is a fiction I paid for",
        "it called it deep and I called it a long blink",
        "my readiness is lying with a straight face",
        "the app said restore and my eyes said invoice",
        "I am being graded by something that was on my wrist",
        "good sleep score, bad bathroom lighting",
        "why is 87 the most insulting number",
        "it thinks I recovered. I was there. I did not.",
        "my bracelet wrote a better night than I lived",
        "the little stars under the score feel like a joke",
        "I opened the app hoping it would agree I feel wrecked",
        "it said optimal and I said okay liar",
        "my body and my dashboard are in different time zones",
        "the ring buzzed proud and my jaw is still at work",
        "I have a silver medal in a sport I lost",
        "the percent is high and the morning is low",
        "why do I let a graph tell me how the night went",
        "it measured motion and called it rest",
        "my watch is gaslighting my face",
        "I screenshot a good night I did not attend",
        "the score wants me to train. I want to sit.",
        "it labeled REM like I should be grateful",
        "green ring, red eyes",
        "I got 100 and I still walked into the kitchen sideways",
        "the app is a cheerful roommate who was not in the bed",
        "why does a number get to be this sure",
        "I woke up and checked if the night counted before I checked if I did",
    ],
)

fam(
    "10-room-vs-body",
    "Information gap",
    "The room did its job. I did not.",
    [
        "the room is quiet and I am not",
        "the dark is doing everything and I am still on",
        "this bedroom looks like night and I look like noon",
        "the pillow is ready and I am still employed",
        "cool air, warm brain",
        "the curtains closed and my thoughts opened",
        "I built a cave and brought a stadium in",
        "the bed is made for a person who arrived",
        "silence is loud when I am the only noise",
        "the lamp is off and the day is still projected on the wall of my head",
        "this room cost money to be this dim and I wasted it",
        "the sheets are cold in a way that should work",
        "I did the room and not the night",
        "blackout curtains, floodlight mind",
        "the fan is steady and I am not",
        "I made the perfect conditions for someone else",
        "the air smells like laundry and I smell like a deadline",
        "this is a sleep room hosting a work meeting",
        "the mattress is quiet. I creak.",
        "I dimmed the world and my pulse did not dim",
        "the window is doing night correctly",
        "I am the only lamp left on",
        "soft pillow, sharp list",
        "the room whispered and I answered in paragraphs",
        "I turned the house down and left myself at full volume",
        "this darkness is rented by a brain that did not sign",
        "the corner is shadows and I am a spreadsheet",
        "I can hear how empty the room is",
        "the bed knows what it is. I am still deciding.",
        "nice room. wrong tenant.",
        "I bought quiet and it does not fit",
        "the nightstand looks peaceful without me",
        "I am too awake for this wallpaper",
        "the rug, the lamp, the whole set, and then me",
        "the room is a closed shop and I am still shopping",
        "I matched the temperature and missed the person",
        "this is what night looks like from the outside of my body",
        "the walls are doing nothing and that should be enough",
        "I staged a bedroom and forgot to exit the day",
        "the dark is available and I am booked",
    ],
)

fam(
    "11-identity-crack",
    "Identity crack",
    "I am not who I am at night.",
    [
        "I used to fall asleep in cars",
        "I used to be a person who slept",
        "I am not a night person and I am still awake",
        "I used to drop at 10 like a stone",
        "I sleep like someone I would give advice to",
        "I used to trust beds",
        "I am a morning person trapped in a 1am body",
        "I used to nap on trains",
        "I do not recognize the person who negotiates with pillows",
        "I used to sleep through storms",
        "I am supposed to be the one who is good at this",
        "I used to blink and it was morning",
        "I sleep like a guest in my own night",
        "I used to laugh at people who had a routine",
        "I am not the sleeper in any story about me",
        "I used to pass out after dinner",
        "I became someone who performs lying down",
        "I used to need 20 minutes. I now need a project plan.",
        "I am a competent adult until the lights go off",
        "I used to sleep at other people's houses with no fear",
        "I do not know when I stopped being easy",
        "I used to wake up in the same century I fell asleep in",
        "I am the friend who used to sleep anywhere",
        "I used to close my eyes as a decision",
        "I sleep like I am being graded",
        "I used to be bored into sleep",
        "I am a person with a bedtime and no sleep time",
        "I used to get heavy without asking",
        "I do not remember the last easy night I did not photograph in my head",
        "I used to think sleep was what happened after the day",
        "I am trying to be the kind of person who just goes to bed",
        "I used to drool on planes",
        "I sleep like an impersonation of rest",
        "I used to not notice the clock",
        "I am someone who now has opinions about pillows",
        "I used to fall asleep talking",
        "I do not feel like the me who could do nights",
        "I used to wake hungry, not hunted",
        "I am a daytime personality with a nighttime glitch",
        "I used to think I would always be able to do this",
    ],
)

fam(
    "12-unwanted-wake",
    "Clock + false finish",
    "I did not choose this wake.",
    [
        "I did not remember deciding to be awake",
        "I woke up and I was already thinking",
        "I came back and the night had not invited me",
        "I surfaced like I forgot to stay under",
        "I was not finished being gone",
        "I woke in the middle of a sentence I was not speaking",
        "I opened my eyes and the dark looked surprised too",
        "I did not choose this version of 3am",
        "I came up for a swallow and stayed for an hour",
        "I woke because a dream put me down carelessly",
        "I am awake in a way that feels accidental",
        "I returned to a room I never left",
        "I woke and immediately owed the day a plan",
        "I was ejected, not risen",
        "I woke thirsty and then I woke ambitious",
        "I did not sit up on purpose",
        "I woke as if someone said my name from the kitchen",
        "I am up and I cannot name the reason which is worse",
        "I woke into the leftover of a thought",
        "I came back too early and too complete",
        "I woke and the blanket felt like evidence",
        "I did not finish the first sleep",
        "I woke with my hands already clenched",
        "I am awake like a light that got flipped from the hall",
        "I woke and started hosting my own brain",
        "I arrived in the night I was supposed to be missing",
        "I woke because my neck voted",
        "I did not want this intermission",
        "I woke and checked the time like that would put me back",
        "I am up and the house is still pretending it is night",
        "I woke mid-turn like a bad edit",
        "I came back with too much personality",
        "I woke and my mouth had been open like I was running",
        "I did not get a choice about this consciousness",
        "I woke and the second night began without a title",
        "I am awake in the cheap seats of my own sleep",
        "I woke because heat gathered and then I stayed for the plot",
        "I did not mean to start tomorrow this early",
        "I woke and immediately became a manager",
        "I came back and could not find the hole I fell through",
    ],
)

fam(
    "13-look-vs-feel",
    "Proof + broken deal",
    "The mirror and the body disagree.",
    [
        "I look worse than I feel and I do not feel good",
        "I feel fine until I see my face",
        "my body says I slept. my face files a dissent.",
        "I look like I lost and I only lay down",
        "I feel 60% and I look 20",
        "the mirror is ruder than the night",
        "I feel hollow and I look busy",
        "I woke up feeling almost okay and then I saw me",
        "my face is doing a worse night than I remember",
        "I feel heavy and I look unwatered",
        "I look like a layover in my own skin",
        "I feel blurry and I look overdrawn",
        "why does my face tell on a night my memory already softened",
        "I feel like I could start and I look like I should sit",
        "my reflection is the only honest recap",
        "I look swollen with a rest I did not receive",
        "I feel thin-sleep and I look thick-night",
        "the bathroom lighting is a critic",
        "I look unrested in a specific way I cannot rub off",
        "I feel okay in the dark and ruined in the tile",
        "my face kept the minutes I lost",
        "I look like I slept in a chair I do not own",
        "I feel one degree off and I look a whole season off",
        "why is my left eye telling a different night than my right",
        "I look concentrated and I was unconscious",
        "I feel like bread left out and I look like the bag",
        "the first photo of the day would be a lie or a confession",
        "I look expensive-tired, not fun-tired",
        "I feel the night in my teeth more than in my memory",
        "my face is puffy with effort I do not recall spending",
        "I look like I argued and I only turned over",
        "I feel grey and I look fluorescent",
        "why do I look more awake than I am allowed to feel",
        "I look like morning already used me",
        "I feel padded and I look creased",
        "the mirror and the mattress are not in the same story",
        "I look like I borrowed a face from 3am",
        "I feel almost human and I look like a draft of one",
        "my cheeks know something my calendar does not",
        "I look slept-on, not slept",
    ],
)

fam(
    "14-effort-tax",
    "Broken deal",
    "I tried and still owe.",
    [
        "I did the routine and my brain still clocked in",
        "I dimmed the lights and I stayed bright",
        "I put the phone away and my thumb kept twitching",
        "I drank the water and woke up dry anyway",
        "I stretched and my jaw undid it",
        "I wrote tomorrow's list and then I wrote it again in the dark",
        "I took the walk and the day followed me home",
        "I showered like that was a border",
        "I did the tea and the tea was just warm",
        "I read the boring page and I still invented a plot",
        "I laid out tomorrow's clothes like a bribe",
        "I closed every tab and opened a better one behind my eyes",
        "I did the breathing and I counted the breathing",
        "I made the room cold and my thoughts ran to stay warm",
        "I put on the quiet show and I analyzed the quiet show",
        "I did not snack and my stomach held a meeting anyway",
        "I brushed my teeth like a closing ceremony",
        "I did the whole wind-down and it was just chores at night",
        "I left the phone in the kitchen and my brain went to get it",
        "I did the lamps and not the leaving",
        "I tried the earlier bedtime and met a longer hallway",
        "I did not drink after 6 and 2pm still found me",
        "I washed my face like I could rinse the day off",
        "I did the stretch on the floor and stood up still at work",
        "I set the alarm with hope like that is a method",
        "I did the journal line and then I narrated the journal line",
        "I tried no ceiling light and my laptop became the sun",
        "I did everything they tell you in the order they tell you",
        "I prepared a perfect night for a person who did not arrive",
        "I tried being good and being good was just more tasks",
        "I stacked the right objects and missed the off-switch",
        "I did the socks, the water, the book, the dark",
        "I tried less caffeine and more disappointment",
        "I earned the night and the night stayed unpaid",
        "I did the ritual so hard it became another job",
        "I tried to deserve sleep",
        "I did the responsible evening and the irresponsible mind",
        "I put effort in the first hour and got taxed on the rest",
        "I tried so correctly that I could not get stupid enough to sleep",
        "I did the work of sleeping and forgot the sleeping",
    ],
)

fam(
    "15-stolen-morning",
    "False finish",
    "Morning arrived already used.",
    [
        "I woke up already late inside",
        "morning found me mid-sentence",
        "I opened my eyes and the day had a head start",
        "I woke up behind a morning I had not met",
        "the day started without asking if I had finished the night",
        "I woke up already apologizing",
        "morning is happening to a person who is not ready to host",
        "I sat up and owed three things before my feet hit",
        "I woke into a day that felt pre-owned",
        "the light is here and I am not assembled",
        "I woke up and the morning was already loud in my chest",
        "I lost the first hour before I stood",
        "I woke up on the back foot of a day that just began",
        "morning arrived like a bill",
        "I opened my eyes and needed a buffer I did not get",
        "I woke up used",
        "the kitchen is too bright for the night I had",
        "I woke up and my first thought was already a reply",
        "morning feels like a continuation, not a start",
        "I came into the day sideways",
        "I woke up and the to-do list had slept better than I did",
        "the morning is crisp and I am crumpled",
        "I woke up missing a version of me who had a runway",
        "daylight is a group project I did not study for",
        "I woke up and immediately needed yesterday back for 20 minutes",
        "the first coffee is a rescue not a pleasure",
        "I woke up already in the hallway of the day",
        "morning is performing and I am still backstage",
        "I woke up and the sun was unreasonably sure of itself",
        "I stepped into a morning that did not wait",
        "I woke up with no on-ramp",
        "the day is a train I am jogging beside",
        "I woke up and my face had already commuted",
        "morning stole the soft hour and left me the sharp one",
        "I woke up in progress",
        "the alarm was the second rude thing. the first was being awake.",
        "I woke up and needed the night to have been longer or kinder",
        "morning is a room I entered without shoes",
        "I woke up already spent on a day that has not charged me yet",
        "I am late to a morning that just started",
    ],
)

fam(
    "16-wrong-place",
    "Almost + object",
    "I can sleep anywhere but the bed.",
    [
        "I can sleep on the couch and not in the bed",
        "I get sleepy in the wrong room",
        "I was gone in the chair and born again under the sheet",
        "the couch knows how to hold me and the bed asks questions",
        "I can sleep in cars and not in my own expensive dark",
        "I nod off at 9 in the living room and debut at 11 in the bedroom",
        "the bed is where I remember I have a life",
        "I can almost sleep sitting up like a coward",
        "the sofa takes me and the mattress interviews me",
        "I get heavy near a screen and light near a pillow",
        "I can sleep at other people's houses like a traitor",
        "hotels work and my bedroom does a presentation",
        "I fall asleep in the glow and wake up in the correct place angry",
        "the recliner is dishonest and effective",
        "I can sleep through a movie and not through a plan to sleep",
        "my body trusts the couch's accidental night",
        "the bed is too intentional",
        "I get the wave on the floor with the dog and lose it in the sheets",
        "I can sleep on a plane with a stranger's elbow",
        "my own pillow is the one that turns the lights on in my head",
        "I doze in daylight like it does not count so it works",
        "the guest room would probably be kinder to me",
        "I can sleep after crying on the bathroom floor and not after brushing my teeth correctly",
        "the car ride home had the sleep the bed wanted",
        "I get pulled under by a boring meeting and pushed up by a quiet mattress",
        "the couch is a loophole",
        "I can sleep in a hoodie on the sofa like a person with no goals",
        "the bed smells like trying",
        "I was out during the ad break and awake for my own wind-down",
        "I can sleep with a light on in the wrong room",
        "my body likes sleep as a side effect",
        "the official night is the one I fail",
        "I can nap in a patch of sun like a cat and not in a designed cave",
        "the mattress is a stage. the couch is a ditch. I need the ditch.",
        "I get sleepy putting a child down and then I become the adult again",
        "I can sleep sitting against a wall at 4pm",
        "the bed is where I become available to myself",
        "I lose the sleepy when I decide it is time",
        "I can sleep through noise that is not mine",
        "the correct pillow is the problem",
    ],
)

fam(
    "17-night-mind",
    "Identity + object",
    "Work starts when I lie down.",
    [
        "I close my eyes and start a meeting",
        "I lie down and my brain opens the laptop",
        "the second my head lands, the day clocks back in",
        "I go horizontal and become management",
        "bed is where I write the email I will not send",
        "I start the performance review of my own afternoon",
        "lying down is my office hours",
        "I put my head down and pick up tomorrow",
        "the pillow is a desk",
        "I replay a conversation with better lines",
        "I do strategy in the dark like that helps anyone",
        "I close the day and it files an appeal",
        "my best ideas arrive when I cannot write them down on purpose",
        "I become employed at the exact moment I try not to be",
        "I hold still and my mind paces",
        "I go to bed as if it were a second shift",
        "I start listing people I forgot to reply to",
        "the dark is a whiteboard",
        "I lie there composing a life I already lived today",
        "I punch out and my brain punches in for unpaid overtime",
        "I start fixing a problem that is not due until Thursday",
        "I get brilliant at 12:20 about a sink",
        "I run the whole workday again with comments",
        "I become the most available I have been all day, to my own head",
        "I close my eyes and open the shared doc",
        "I do career thoughts like a hobby at 1am",
        "I lie down and remember every unfinished tab",
        "I start a presentation for an audience of ceiling",
        "I get sudden competence when it cannot be used",
        "I put the body to bed and leave the job running",
        "I negotiate a conversation that already ended",
        "I do inventory of my own competence in the worst lighting",
        "I go still and the to-do list stands up",
        "I start teaching a class nobody enrolled in",
        "I lie there being helpful to a day that is over",
        "I become a project manager of nothing",
        "I close my eyes and my calendar breathes",
        "I do the meeting I avoided, perfectly, too late",
        "I clock into a company that is just me and a pillow",
        "I start work because the house finally got quiet enough to think",
    ],
)

fam(
    "18-weekend-lie",
    "Broken deal",
    "Extra hours made it worse.",
    [
        "I slept in and I feel worse",
        "Saturday gave me more hours and a thicker head",
        "I caught up and I did not catch up",
        "a late morning stole the next night",
        "I slept until 11 and woke up in the wrong day",
        "weekend sleep is a rumor I keep funding",
        "I stayed in bed like that would refund Friday",
        "I woke at noon and the light felt like an argument",
        "I tried to store sleep and it went bad",
        "Sunday night is the tax on Saturday morning",
        "I slept long and woke late to myself",
        "the extra hours were just extra lying",
        "I treated the weekend like a warehouse",
        "I woke from a long sleep hungover without the fun",
        "I pushed wake time and dragged the whole clock",
        "I slept in and now 10pm feels like afternoon",
        "Sunday 4pm already feels like a school night I did not attend",
        "I banked sleep and bounced a check at 1am",
        "two slow mornings and I lost Monday in advance",
        "I let the night run long and the morning ran me",
        "I slept like I was owed and woke like I overdrew",
        "the lie-in was a different time zone",
        "I woke up still tired with more evidence",
        "I used the weekend to confuse the only clock I had",
        "I stayed down and the day got away in a way that still tired me",
        "long sleep, short soul",
        "I tried to get ahead and got behind the sun",
        "Saturday night I was not sleepy because Saturday morning I was greedy",
        "I slept the way people say to and I felt like luggage",
        "the weekend night is louder because the morning was softer",
        "I woke from extra sleep needing a nap like a joke",
        "I gave myself permission and my body took chaos",
        "I slept in and missed the only easy light of the day",
        "Sunday evening I am jetlagged in my own apartment",
        "I stacked late nights like they were a rest strategy",
        "I woke at 10 feeling like I skipped a night I was present for",
        "the long morning made a mean night",
        "I tried to recover on a calendar and not in a body",
        "I slept more and recognized myself less",
        "weekend hours are not the same currency",
    ],
)

fam(
    "19-body-receipt",
    "Proof before name",
    "A part reported the night.",
    [
        "my jaw is sore and I was asleep",
        "my neck paid for a night I do not remember",
        "I woke up and my teeth had a job",
        "my tongue is dry like I ran",
        "my shoulders are up around a sleep I was supposed to drop",
        "I have a pillow crease that looks like a scar from trying",
        "my hips ache like I held a position in a meeting",
        "I woke with a hand numb from a night of gripping",
        "my throat is scratchy from a mouth that would not close",
        "I have a knot under my shoulder blade named 2am",
        "my calves are tight like I stood in my sleep",
        "I woke and my low back filed the report",
        "my lips are cracked from air I breathed too long",
        "I have a sore spot on my scalp from the same turn",
        "my wrists hurt from a phone I already put down",
        "I woke with my eyebrows still raised",
        "my nose is stuffed from a pillow height I keep choosing",
        "I have morning tightness that feels like leftover effort",
        "my ears are ringing in a quiet room",
        "I woke and my stomach was loud in a night kitchen way",
        "my knees feel older than the date",
        "I have a bite on the inside of my cheek I do not remember placing",
        "my collarbone is tender from a side I would not leave",
        "I woke with my toes clenched",
        "my sinuses did a whole weather system",
        "I have a crick that is just the night in one line",
        "my chest feels braced like I was ready",
        "I woke and my ankles were hot",
        "my hairline is damp and the room is not",
        "I have a numb lip from sleeping like a statue",
        "my eye socket aches in a way that feels like squinting at dreams",
        "I woke with my tongue stuck to a dry roof",
        "my right shoulder is the one that stayed employed",
        "I have fingerprint marks in my palm from my own nails",
        "my hips click like I stored the day in the joints",
        "I woke and my face muscles were tired of being a face",
        "my throat clicked when I swallowed the first time",
        "I have a bruise-feeling on my cheek from a seam",
        "my whole left side is the receipt",
        "I woke already stretching a night I was not invited to feel",
    ],
)

fam(
    "20-face-bill",
    "Information gap",
    "Sleep charged my face.",
    [
        "sleep billed my face",
        "I asked for rest and got swelling",
        "my face looks like it worked the night I took off",
        "I woke up puffier than the day I was tired",
        "sleep left fingerprints on my cheeks",
        "I look salted",
        "my face held water like a grudge",
        "I went to bed sharp and woke up blurred",
        "the night inflated me",
        "I have morning face that looks like an argument with a pillow",
        "my cheeks are loud",
        "I look like I drank a night I did not drink",
        "sleep did a bad edit on my jawline",
        "I woke up thicker in the places that photograph",
        "my face is shiny and exhausted at the same time",
        "I look like rising dough with a deadline",
        "the night collected in my eyelids first",
        "I have a crease that will take an hour of being a person to leave",
        "my face looks overhydrated and thirsty",
        "I woke up looking like the pillow won",
        "sleep pressed me into a cheaper version",
        "I have one swollen side like I slept in a story",
        "my mouth corners are dry and my lids are wet",
        "I look puffy with a specific sadness of horizontal time",
        "the night sat on my face and stood up slowly",
        "I woke looking like I retained the whole evening",
        "my skin looks tired of being skin overnight",
        "I have a pillow map on my cheek",
        "sleep made me look like I had a secret I did not enjoy",
        "I woke up and my face needed a loading screen",
        "my features arrived at different times",
        "I look like I slept in humidity that was just me",
        "the night left a shine I did not earn with rest",
        "I have morning puff that feels like unpaid overtime in the tissue",
        "my face is tight and loose in the wrong places",
        "I woke up looking soaked and unwatered",
        "sleep charged interest on my under-eyes",
        "I look like a thumbnail of tired",
        "my face is the invoice",
        "I went dark to look better and looked more like the dark",
    ],
)

fam(
    "21-unsaid-want",
    "Unsaid want",
    "I want the night, not the sleep.",
    [
        "I do not want to sleep I want the house to stay mine",
        "I am protecting the only quiet I get",
        "I am not tired of being awake I am tired of the performance of going to bed",
        "I want one more hour that belongs to nobody",
        "I stay up because it is the first time today no one needs me",
        "I am not chasing rest I am chasing a room with no tasks",
        "I want the lamp more than I want the morning",
        "I keep the night because daytime is rented",
        "I am awake on purpose and still mad about it",
        "I want to be left by the day, not tucked in by a routine",
        "I stay up to feel like the main character of a nothing evening",
        "I am not avoiding sleep I am extending the only unlocked door",
        "I want silence that I chose",
        "I linger because tomorrow starts the asking again",
        "I am greedy for empty time and I pay in morning face",
        "I want to sit in the dark without it being a method",
        "I stay awake to keep a little of the day I did not get",
        "I am using night as a spare room",
        "I want privacy more than I want 8 hours",
        "I refuse the bedtime because it feels like someone else's idea of good",
        "I am not wired I am unwilling to close the shop",
        "I want the house at 11 more than the person at 7",
        "I stay up to hear the fridge and call it peace",
        "I am stealing tonight from tomorrow and I know",
        "I want to finish being a person before I become a sleeper",
        "I keep my eyes open like that keeps the apartment mine",
        "I am not scared of tomorrow I am not done with today",
        "I want a night that is not a prelude",
        "I stay up because sleep feels like losing the last room",
        "I am awake because this is the only unsupervised hour",
        "I want to waste time that is actually mine",
        "I will not go to bed until I feel like I lived a little",
        "I am holding the quiet hostage",
        "I want rest without surrender",
        "I stay up to feel unneeded",
        "I am not procrastinating sleep I am rationing solitude",
        "I want the night to last until I feel caught up on being alone",
        "I keep watch because daytime is a group project",
        "I am awake for the same reason I lock the bathroom door",
        "I want sleep later, after I have had a life for 20 minutes",
    ],
)

fam(
    "22-missing-manual",
    "Forbidden question",
    "Nobody warned me mornings look like this.",
    [
        "nobody told me mornings could look like this",
        "why did no one say sleep can make you look worse",
        "I thought the tired face was for people who did not try",
        "nobody mentioned the 3am shift in a normal life",
        "why is this not in the brochure of being a person",
        "I thought adults just went to bed",
        "nobody said the first hour of morning might be a negotiation",
        "I was told to get 8 hours like that was a button",
        "why did they talk about nights like they were simple math",
        "nobody warned me I would miss being bored at 10",
        "I thought red eyes meant I had a story. I only had a pillow.",
        "nobody said you can do everything right and still meet 3:07",
        "why is the official advice written for a different animal",
        "I thought sleep was what happened if you were tired enough",
        "nobody mentioned the night mind getting promoted",
        "I was not told the couch would become a rival",
        "why did they skip the part where you do not want to sleep",
        "nobody said your face can keep a night you forgot",
        "I thought morning was a reset and it is a leftover",
        "nobody told me quiet can be the thing that wakes you",
        "I was sold a routine like it was a key and it is a chore list",
        "why does every guide assume I want to go to bed",
        "nobody said the tracker would become a third person in the room",
        "I thought darkness was enough infrastructure",
        "nobody mentioned waking up already behind a day that just started",
        "I was not told Saturday morning could ruin Sunday night",
        "why did they not say the hours can bounce",
        "nobody warned me I would become someone with a pillow opinion",
        "I thought kids were the only reason nights get weird",
        "nobody said you can be sleepy in the wrong room on purpose",
        "I was not prepared for the politics of one lamp",
        "why is the missing chapter the one about not wanting the night to end",
        "nobody told me my jaw would moonlight",
        "I thought being tired was the ticket and I keep losing it at the door",
        "nobody said you can wake up thirsty from a night of nothing",
        "I was not told the first thought could be a meeting",
        "why did they make sleep sound like manners",
        "nobody mentioned the specific grief of almost",
        "I thought I would always know how to do this",
        "nobody gave me a manual for a face that looks like it worked overnight",
    ],
)

fam(
    "23-one-variable",
    "Information gap",
    "I only changed one thing.",
    [
        "I only moved my bedtime and the whole week slid",
        "I only had the coffee later",
        "I only left the big light on until 10",
        "I only watched one more episode",
        "I only skipped the walk",
        "I only slept in once",
        "I only moved the phone to the bed",
        "I only had the late salty thing",
        "I only took the nap that felt harmless",
        "I only closed the laptop in the same room I sleep",
        "I only changed the pillow and now I have a neck story",
        "I only drank the wine because the day was long",
        "I only checked the score first",
        "I only sat on the couch to rest my eyes",
        "I only answered one email after 9",
        "I only kept the hallway light for the kid",
        "I only made the room warmer because I was sick of being brave",
        "I only skipped morning light because I was late",
        "I only used the phone as an alarm again",
        "I only had water and still woke up like I'd been talking",
        "I only changed jobs to work from home and the day never ended",
        "I only started sleeping next to someone who is good at it",
        "I only bought blackout curtains and discovered my mind",
        "I only stopped the nightly show and heard the house",
        "I only added a tracker and started performing for it",
        "I only moved cities and the dark arrives wrong",
        "I only had a baby and now the night has shifts",
        "I only started caring and that was the variable",
        "I only went to bed proud of being early",
        "I only opened the shade at 5 because a truck did",
        "I only said I would rest and turned it into a project",
        "I only switched to the other side of the bed",
        "I only had a quiet Sunday and it made Monday violent",
        "I only used the guest blanket",
        "I only thought about tomorrow on purpose",
        "I only charged the watch next to my head",
        "I only ate later because the house finally sat down",
        "I only skipped the wind-down because I was already late to sleep",
        "I only changed one lamp",
        "I only decided tonight mattered and then it wouldn't start",
    ],
)

fam(
    "24-second-wake",
    "Almost + clock",
    "The second wake keeps the house.",
    [
        "the first wake I can ignore. the second one owns me.",
        "I came back the second time and stayed",
        "the second wake is the real night",
        "I can forgive 2am. 3:20 keeps the keys.",
        "I woke, I almost made it, I woke wiser and sadder",
        "the second time I opened my eyes I was employed",
        "I get one free return. the next one charges.",
        "the second wake brings a list",
        "I rolled back once and the second roll failed",
        "after the second wake I start living in the dark on purpose",
        "I can fall back from the first. the second wants a conversation.",
        "the encore is worse than the show",
        "I woke twice and the second one remembered my name",
        "the first wake is a glitch. the second is a decision I did not make.",
        "I lost the night on the replay",
        "the second wake turns the bedroom into a waiting room",
        "I can pretend the first one did not happen",
        "after the second I start planning breakfast like a hostage",
        "the second wake is when I check the time and lose",
        "I came up twice and the water was colder",
        "the first return I was still a sleeper. the second I was a person.",
        "I can drop after one interruption. two makes a plot.",
        "the second wake invites the day in street clothes",
        "I woke, I bargained, I woke and the bargain was over",
        "the second one is when my jaw reports",
        "I get a draft night and then a final night that is just thinking",
        "the second wake has opinions about tomorrow",
        "I can love the first darkness. the second darkness is administrative.",
        "after two wakes I am just lying in a room",
        "the second wake is a roommate turning the light on in my head",
        "I went back and the bed had changed sides",
        "the first wake is noise. the second is me.",
        "I can close the first tab. the second tab is the browser.",
        "the second wake starts the unofficial morning at 4",
        "I returned twice and unpacked",
        "the second time I was too awake to be innocent",
        "I can float after one. two sinks me into the mattress as a thinker.",
        "the second wake is when I become available to every leftover",
        "I woke again and this time I stayed to keep watch",
        "the night ended the second time I knew I was awake",
    ],
)

fam(
    "25-proof-cold",
    "Proof before name",
    "Evidence with no title.",
    [
        "this is my face after a full night",
        "this is the eye that slept",
        "this is what 8 hours looked like on me",
        "this is the crease I did not ask for",
        "this is morning without the story",
        "this is the pillow side",
        "this is a rested person apparently",
        "this is the red they said sleep would clear",
        "this is my mouth after I was supposed to be gone",
        "this is the hair of someone who fought a sheet",
        "this is 3:07's leftover",
        "this is the swelling I earned by lying still",
        "this is my Tuesday face on a night I behaved",
        "this is what the watch called great",
        "this is not a late night. this is a night.",
        "this is the look I get for doing it right",
        "this is my skin after darkness",
        "this is the jaw that would not quit",
        "this is a bathroom mirror, no filter, no lesson yet",
        "this is the eye that worked the night shift",
        "this is after I finally slept",
        "this is the unedited morning",
        "this is what I get for staying in bed",
        "this is my face when the hours were legal",
        "this is not glamorous tired. this is receipt tired.",
        "this is the puffy one",
        "this is me meeting daylight",
        "this is the night still sitting on my lids",
        "this is a full sleep and a half face",
        "this is the proof I do not need a caption for",
        "this is after the routine",
        "this is the opposite of a glow",
        "this is my own night in the harsh bulb",
        "this is what I look like when I do not have a story",
        "this is the morning I paid for",
        "this is sleep on my face, not in it",
        "this is the still from a night with no plot",
        "this is me, post-dark",
        "this is the picture I would not post if I were teaching",
        "this is why I asked why should I sleep",
    ],
)


def main() -> None:
    all_hooks: list[tuple[int, str, str, str, str]] = []
    n = 0
    for slug, mother, gap, hooks in FAMILIES:
        for h in hooks:
            n += 1
            all_hooks.append((n, slug, mother, gap, h))

    if n != 1000:
        raise SystemExit(f"expected 1000 hooks, got {n}")

    lowered = [h.lower().strip() for *_, h in all_hooks]
    if len(set(lowered)) != 1000:
        seen: set[str] = set()
        dups = []
        for x in lowered:
            if x in seen:
                dups.append(x)
            seen.add(x)
        raise SystemExit(f"duplicate hooks: {dups[:20]}")

    bad = [(i, h) for i, *_, h in all_hooks if BANNED.search(h)]
    if bad:
        raise SystemExit(f"banned language: {bad[:10]}")

    lines = [
        "# SleepAlb — 1,000 curiosity hooks",
        "",
        "Spoken openers for Reels, Shorts, TikTok, and Pin titles.",
        "Each line is supposed to leave a **gap**. If you add the reason in the same breath, you spent the watch.",
        "",
        "Mothers, rotations, and the first-12-seconds hold: [`01-curiosity-patterns.md`](./01-curiosity-patterns.md).",
        "How a finished post ships: [`00-sleepalb-direction-strategy.md`](./00-sleepalb-direction-strategy.md).",
        "",
        "Do not run L0 critic on this file. Hooks are not captions.",
        "",
        f"**Count:** {n} unique lines. 25 families × 40.",
        "",
    ]

    current = None
    for i, slug, mother, gap, h in all_hooks:
        if slug != current:
            current = slug
            title = slug.split("-", 1)[1].replace("-", " ")
            lines += [
                "---",
                "",
                f"## {slug} — {title}",
                "",
                f"**Mother:** {mother}  ",
                f"**Gap:** {gap}",
                "",
            ]
        lines.append(f"{i}. {h}")
        lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {n} hooks → {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()



